In [1]:
# ==========================================================
# STEP 1 : Import Required Libraries
# ==========================================================

import pandas as pd
import os

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
# ==========================================================
# STEP 2 : Load Combined Metadata
# ==========================================================

metadata = pd.read_csv("combined_metadata.csv")

print("Metadata Loaded Successfully!")

print("\nTotal Records :", len(metadata))

Metadata Loaded Successfully!

Total Records : 800

In [3]:
# ==========================================================
# STEP 3 : Display First Five Records
# ==========================================================

metadata.head()

            study_id  gender  age findings   dataset
0  CHNCXR_0001_0.png    Male   45   normal  Shenzhen
1  CHNCXR_0002_0.png    Male   63   normal  Shenzhen
2  CHNCXR_0003_0.png  Female   48   normal  Shenzhen
3  CHNCXR_0004_0.png    Male   58   normal  Shenzhen
4  CHNCXR_0005_0.png    Male   28   normal  Shenzhen

In [4]:
# ==========================================================
# STEP 4 : Display Unique Findings
# Purpose :
# Check all disease categories available in the dataset.
# ==========================================================

print("Unique Findings:\n")

for finding in sorted(metadata["findings"].unique()):
    print(finding)

Unique Findings:

1.bilateral secondary PTB  with right upper atelectasis;2.right pleural adhesions;3.left compensatory emphysema
1.secondary PTB  in the right upper field; 2.small tuberculoma; 3.right pleural thickening and adhesions
12x9mm nodule LUL, consistent with large granuloma or some other type of a solitary pulmonary nodule
Bilateral secondary PTB
Bilateral secondary PTB  with most lesions calcified
Bilateral secondary PTB , right pleural change after decortication
Bilateral secondary PTB with left lower field pneumonia
Bilateral secondary PTB, left encapsulated intrathoracic fluid
CXR similar to prior views 1M and 2M ago with some slight improvement; on HRZ(E)x2 months, AFB smears neg now, will switch to HR only (same pt as MCUCXR_0166_1, MCUCXR_0162_1)
LUL inactive scars and some volume loss. h/o treatment 5 years ago.
LUL infiltrate, ? small areas of cavitation, IMP: active TB
Left PTB
Left PTB, left pleural thickening
Left secondary PTB in the upper and middle fields, mainly  fibrous  lesions
NO REPORT (same pt as MCUCXR_0162_1)
Old PTB in the right upper field
PTB
PTB  in the right upper field
PTB in the bilateral upper and middle field
PTB in the bilateral upper field
PTB in the bilateral upper fields
PTB in the bilateral upper fields, left pleurisy
PTB in the left lower field
PTB in the left upper field
PTB in the middle lower field
PTB in the right lower field
PTB in the right upper field
PTB in the right upper field,COPD
RUL apical fibrotic disease with some calcifications; extensive irregular infiltrates in left lung with a large area of cavitation/ findings consistent with old inactive disease in RL and new active TB in LL. On the lordotic view, in the rt apex a large thin walled cavity is visible, making active disease in the area likely as well.
RUL cavitary infiltrate; positive smear
RUL fibrocavitary disease with volume loss and tracheal deviation to right; COPD scoliosis;
RUL infiltrate consistent with TB
Right PTB
Right PTB with fibrous changes
Right pneumothorax, Right upper PTB, bilateral widespread infection
Right secondary PTB
Right secondary PTB in the upper and middle fields
Right secondary PTB,mainly hyperplastic lesions
Rt apical scarring. LUL scars and some infiltrates as well; findings consistent with TB; ?active
STB
TB
active PTB with compicating CHF condition
active TB; cavitary infiltrarte LUL; non-consolidated;
bilateral PTB
bilateral PTB ?right pleurisy with pleural effusion
bilateral PTB,  right upper lobe atelectasis
bilateral PTB, right pleurisy
bilateral PTB, with cavity formation in right upper field
bilateral PTB, with left pleural effusion
bilateral PTB,right upper field atelectasis
bilateral acute hematogenous disseminated PTB
bilateral calcified granulomas scars consistent with inactive TB.
bilateral changes of cavitary TB in upper lobes, more extensive on the right; the RML appears to be involved as well.
bilateral hematogenous disseminated PTB
bilateral miliary nodules diffusely with RML infiltrate and right pleural effusion; an old calcified granuloma is present behind heart in the LLL; all findings consistent with active TB
bilateral secondary PTB
bilateral secondary PTB  with pleural thickening
bilateral secondary PTB  with right pleural thickening
bilateral secondary PTB  with right pneumothorax
bilateral secondary PTB with multiple cavitations
bilateral secondary PTB,mainly hyperplastic lesions
bilateral subacute hematogenous disseminated PTB
calcified granuloma LUL behind 4th rib anterior
cavitary disease RUL with possible small loculated pneumothorax adjacent; has multiuple coarse nodules in RLL as well as lesser amounts in LLL; pt has h/o prior treatment 1Y (6Y ago); no comparison films available; relapsed disease highly likely. pt grew NTM from several specimens, not MTB.
cavitary fibronodular infiltrate RUL. typical appearance of active TB.
cavitary infiltrate near left hilum consistent with TB in superior segment LLL
cavitary nodular infiltrate in RUL; active TB
dense scarring in LUL with volume loss, lesser scarring in RUL; appears similar to old filmes from 3Y ago and 4Y ago. Treated 4Y ago for 6M for INH resistant TB
extensive cavitary TB smear and culture positive involving LUL lungula and some areas in rt lung as well; pt had previously normal CXR (1Y ago) but positive TST and contact with active case
extensive infiltrates bilaterally with large cavity in RUL and a moderate pleural effusion on the left. AFB smears and RNA probes pos for MTB. Active TB, cavitary.
h/o TB rx in xxx 44Y ago with IN PAS SM; has rt apical dense fibrosis, calcification rt lower lung and pleural angle blunting; all compared with inactive disease and h/o treatment.
has inactive appearing scars in LUL; h/o treatment in hospital 17Y ago for 6M in xxx. No comparison films. Recommend followup CXR in 6M. Findings consistent with inactive treated disease.
improved LUL infiltrate and cavity. Active TB on therapy.
improved infiltrates in both lungs; a cavity is now visible in lingula compared with 1M ago. culture positive, pan-sensitive, on HRZ(E) since 1M
improvements after Rx. Has pleural, pulmonary, and probably percardial TB, pan-sensitive
improvements. LUL cavity has closed.
improving infiltrate in LUL
improving infiltrate, active TB
improving rt pleural effusion and the RUL infiltrate is less apparent
inactive TB scars
inactive TB scars LUL
inactive TB scars LUL, unchanged for 2Y, pt previously treated DOT (17Y ago) for pan-sensitive disease
inactive and partly calcified scars and granulomas in RUL. pt completed 4HRZE 4HP DOT for neg culture smear (positive disease)
inactive appearing RUL TB scars
inactive scars RML. has completed treatment
inactive scars RUL
inactive scars unchanged for 6M
large infiltrate RUL with cavitation plus infiltrate in RML. consistent with active cavitary TB
large right pleural effusion, positive TST, TB pleural effusion likely
left PTB
left PTB,left pleurisy
left PTB,pleural thickening
left pleural effusion; best seen on lateral view; with some scar and soft infiltrates in the LUL on the PA and lordotic views; active TB on pleura and lung likely
left secondary PTB
left secondary PTB,right pleural effusion
left upper PTB, left pleurisy
normal
on Rx for culture proven TB. has been clearing of infiltrates in te rt lung. thre is some re-accomodation of pleural fluid along lateral left chest wall.
peripheral homogeneous infiltrate LUL; active pneumonia likely
persistent rt pleural peel with some interval improvement with focal atelectasis in rt lung; anterior wedging of T5, T6 with loss of intervertebral disc space. Findings consistent with h/o spinal TB and pleural TB. Currently on Rx.
pleural TB, on treatment
positive improvement in cavities, infiltrates, and left effusion
right PTB,right pneumothorax
right lower field PTB
right secondary PTB
right secondary PTB  with bilateral  pleurisy
right secondary PTB, right pleurisy with  pleural effusion
right upper PTB
right upper PTB with fibrous changes
right upper PTB, pleural adhesions in  left lower field
right upper field PTB
right upper pneumonia
rt pleural effusion some infoltrate likely in outer RUL
rt pleural effusion with some nodular infiltrate in rt lower lung; there are findings also of previous cardiac surgery; suspicious for active TB.
scoliosis to the left with some scarring in LLL and over the left apex; calcified granuloma in the rt lung. could be related to old TB.
secondary PTB  in the bilateral upper field
secondary PTB  in the bilateral upper fields
secondary PTB  in the left lower field
secondary PTB  in the left upper field
secondary PTB  in the right  middle field
secondary PTB  in the right upper field
secondary PTB  in thel left upper field
secondary PTB in the bilateral upper and middle fields, mainly fibrous  lesions
secondary PTB in the bilateral upper field
secondary PTB in the right upper field
secondary PTB in the right upper field,mainly hyperplastic lesions
small LUL calcified granuloma; pt on rx for culture positive psoas abscess with abdominal lymphadenopathy since 6M
smear positive, active TB LUL apex
stable CXR since 6M; off Rx since 6M (same pt as MCUCXR_0113_1)
stable inactive scars in RUL; post treatment for abscillary TB
suspicious active disease
worsening diffuse infiltrate bilaterally with fine nodular appearance; recent PCP treatment; recurrent PCP likely although miliary TB is also observed.

In [5]:
# ==========================================================
# STEP 5 : Count Images in Each Finding
# ==========================================================

print(metadata["findings"].value_counts())

findings
normal                                                                                                                                                                406
bilateral PTB                                                                                                                                                          61
Right PTB                                                                                                                                                              45
PTB in the right upper field                                                                                                                                           27
left PTB                                                                                                                                                               19
                                                                                                                                                                     ...
calcified granuloma LUL behind 4th rib anterior                                                                                                                         1
inactive scars RUL                                                                                                                                                      1
Rt apical scarring. LUL scars and some infiltrates as well; findings consistent with TB; ?active                                                                        1
left pleural effusion; best seen on lateral view; with some scar and soft infiltrates in the LUL on the PA and lordotic views; active TB on pleura and lung likely      1
large infiltrate RUL with cavitation plus infiltrate in RML. consistent with active cavitary TB                                                                         1
Name: count, Length: 132, dtype: int64

In [6]:
# ==========================================================
# STEP 6 : Create Binary Labels
# ==========================================================

# Normal  -> 0
# TB      -> 1

metadata["label"] = metadata["findings"].apply(
    lambda x: 0 if str(x).strip().lower() == "normal" else 1
)

print("Binary Labels Created Successfully!")

Binary Labels Created Successfully!

In [7]:
# ==========================================================
# STEP 7 : Check Label Distribution
# ==========================================================

print(metadata["label"].value_counts())

label
0    406
1    394
Name: count, dtype: int64

In [8]:
# ==========================================================
# STEP 8 : Verify Labels
# ==========================================================

metadata.head(10)

            study_id  gender  age findings   dataset  label
0  CHNCXR_0001_0.png    Male   45   normal  Shenzhen      0
1  CHNCXR_0002_0.png    Male   63   normal  Shenzhen      0
2  CHNCXR_0003_0.png  Female   48   normal  Shenzhen      0
3  CHNCXR_0004_0.png    Male   58   normal  Shenzhen      0
4  CHNCXR_0005_0.png    Male   28   normal  Shenzhen      0
5  CHNCXR_0006_0.png    Male   60   normal  Shenzhen      0
6  CHNCXR_0007_0.png  Female   53   normal  Shenzhen      0
7  CHNCXR_0008_0.png    Male   48   normal  Shenzhen      0
8  CHNCXR_0009_0.png  Female   71   normal  Shenzhen      0
9  CHNCXR_0010_0.png  Female   59   normal  Shenzhen      0

In [9]:
# ==========================================================
# STEP 9 : Save Final Labeled Metadata
# ==========================================================

metadata.to_csv("labeled_metadata.csv", index=False)

print("="*50)
print("Labeled Metadata Saved Successfully!")
print("File Name : labeled_metadata.csv")
print("="*50)

==================================================
Labeled Metadata Saved Successfully!
File Name : labeled_metadata.csv
==================================================