In [2]:
# =============================================================================
# NOTEBOOK 19 — CELL 1
# FINAL RESEARCH RESULTS INTEGRATION
# FROZEN ARTIFACT + FINAL MODEL AUDIT
#
# ANALYSIS ONLY
# NO TRAINING
# NO FINE-TUNING
# NO TEST TUNING
# =============================================================================

from pathlib import Path
import json
import pandas as pd
import numpy as np


# =============================================================================
# 1. ROOT
# =============================================================================

FINAL_ROOT = Path(
    r"C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation"
) / "QC" / "Clean_PSPNet_CXR_Cohort" / "FINAL_FROZEN_CLEAN_COHORT"

NB19_ROOT = FINAL_ROOT / "Notebook19_Final_Research_Results_Integration"
CELL1_ROOT = NB19_ROOT / "Cell1_Final_Frozen_Artifact_Audit"

CELL1_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

print("=" * 90)
print("NOTEBOOK 19 — CELL 1")
print("FINAL RESEARCH RESULTS INTEGRATION")
print("FROZEN ARTIFACT + FINAL MODEL AUDIT")
print("=" * 90)


# =============================================================================
# 2. EXACT VERIFIED PATHS
# =============================================================================

FROZEN_COHORT = (
    FINAL_ROOT /
    "Notebook07_Cell24F_FINAL_CLEAN_PSPNet_CXR_COHORT.csv"
)

AUTHORITATIVE_SPLIT = (
    FINAL_ROOT /
    "MASTER_CONDITION_LEVEL_SPLIT" /
    "Notebook08_Cell25_FINAL_1976_Condition_Level_Split.csv"
)

# -------------------------------------------------------------------------
# CXR
# -------------------------------------------------------------------------

CXR_PREDICTIONS = (
    FINAL_ROOT /
    "CoAtNet_Test_Evaluation_Run2_10G" /
    "Cell2_Final_Test_Predictions" /
    "Notebook10G_Cell2_Run2_FINAL_396_Test_Predictions.csv"
)

CXR_METRICS = (
    FINAL_ROOT /
    "CoAtNet_Test_Evaluation_Run2_10G" /
    "Cell3_Final_Test_Metrics" /
    "Notebook10G_Cell3_Run2_FINAL_Test_Metrics.json"
)

CXR_CHECKPOINT = (
    FINAL_ROOT /
    "CoAtNet_Training_Run2_10C" /
    "checkpoints" /
    "Notebook10C_Run2_Best_Validation_ROC_AUC.pth"
)

# -------------------------------------------------------------------------
# Genomic prediction/checkpoint
# -------------------------------------------------------------------------

GENOMIC_PREDICTIONS = (
    FINAL_ROOT /
    "Genomic_Preparation_13" /
    "Cell8_Frozen_Test_Evaluation" /
    "Notebook13_Cell8_FINAL_Frozen_Test_Predictions.csv"
)

GENOMIC_CHECKPOINT = (
    FINAL_ROOT /
    "Genomic_Preparation_13" /
    "Cell7_Transformer_Training" /
    "Notebook13_Cell7_Best_Validation_ROC_AUC.pth"
)

# -------------------------------------------------------------------------
# IMPORTANT:
# Genomic metrics filename/location is NOT assumed.
# It is resolved recursively below.
# -------------------------------------------------------------------------

GENOMIC_METRICS_CANDIDATES = list(
    FINAL_ROOT.rglob(
        "*Notebook13*Cell8*Metrics*.json"
    )
)

if len(GENOMIC_METRICS_CANDIDATES) == 0:

    GENOMIC_METRICS_CANDIDATES = list(
        FINAL_ROOT.rglob(
            "*Cell8*Metrics*.json"
        )
    )

if len(GENOMIC_METRICS_CANDIDATES) == 0:

    raise FileNotFoundError(
        "Could not locate the actual Notebook 13 Cell 8 "
        "genomic metrics JSON anywhere under FINAL_ROOT.\n\n"
        f"FINAL_ROOT:\n{FINAL_ROOT}\n\n"
        "Files containing 'Cell8' and 'Metrics' that were found:"
        + "\n".join(
            str(p)
            for p in FINAL_ROOT.rglob("*Cell8*")
            if p.is_file()
        )
    )

# Remove duplicates while preserving order
GENOMIC_METRICS_CANDIDATES = list(
    dict.fromkeys(
        GENOMIC_METRICS_CANDIDATES
    )
)

if len(GENOMIC_METRICS_CANDIDATES) > 1:

    print("\nMultiple genomic metric candidates found:")

    for i, p in enumerate(
        GENOMIC_METRICS_CANDIDATES,
        start=1
    ):
        print(f"{i}. {p}")

    # Prefer the exact known final-metrics naming if present.
    exact_name_matches = [
        p for p in GENOMIC_METRICS_CANDIDATES
        if p.name ==
        "Notebook13_Cell8_FINAL_Frozen_Test_Metrics.json"
    ]

    if len(exact_name_matches) == 1:

        GENOMIC_METRICS = exact_name_matches[0]

    else:

        # If multiple remain, do NOT guess.
        raise RuntimeError(
            "Multiple genomic metrics files were found and "
            "none can be selected safely without guessing.\n\n"
            + "\n".join(
                str(p)
                for p in GENOMIC_METRICS_CANDIDATES
            )
        )

else:

    GENOMIC_METRICS = GENOMIC_METRICS_CANDIDATES[0]


# -------------------------------------------------------------------------
# Multimodal
# -------------------------------------------------------------------------

MULTIMODAL_PREDICTIONS = (
    FINAL_ROOT /
    "Multimodal_15" /
    "Cell6_Frozen_Test_Evaluation" /
    "Notebook15_Cell6_FINAL_Frozen_Test_Predictions.csv"
)

MULTIMODAL_METRICS = (
    FINAL_ROOT /
    "Multimodal_15" /
    "Cell6_Frozen_Test_Evaluation" /
    "Notebook15_Cell6_FINAL_Frozen_Test_Metrics.json"
)

MULTIMODAL_CHECKPOINT = (
    FINAL_ROOT /
    "Multimodal_15" /
    "Cell4_Fusion_Training" /
    "checkpoints" /
    "Notebook15_Cell4_Best_Multimodal_Validation_ROC_AUC.pth"
)


# =============================================================================
# 3. NOTEBOOK 17
# =============================================================================

NB17_SUMMARY = (
    FINAL_ROOT /
    "Notebook17_Cell6_Final_XAI_Summary" /
    "Notebook17_Cell6_FINAL_XAI_Summary.json"
)


# =============================================================================
# 4. NOTEBOOK 18
# =============================================================================

NB18_ROOT = (
    FINAL_ROOT /
    "Notebook18_Final_Multimodal_Explainability_Analysis"
)

NB18_SUMMARY = (
    NB18_ROOT /
    "Cell5_Final_Multimodal_Explainability_Summary" /
    "Cell5_Complete_Audit.json"
)

NB18_CONTRIBUTION = (
    NB18_ROOT /
    "Cell2B_Modality_Contribution" /
    "Notebook18_Cell2B_FINAL_Frozen_Multimodal_Modality_Contribution.csv"
)

NB18_STATS = (
    NB18_ROOT /
    "Cell3_Modality_Contribution_Statistical_Analysis" /
    "Cell3_Primary_Statistics.csv"
)

NB18_FIGURE_MANIFEST = (
    NB18_ROOT /
    "Cell4_Modality_Contribution_Figures" /
    "Notebook18_Cell4_Figure_Manifest.csv"
)


# =============================================================================
# 5. ARTIFACT AUDIT
# =============================================================================

required_files = {

    "Frozen cohort":
        FROZEN_COHORT,

    "Authoritative split":
        AUTHORITATIVE_SPLIT,

    "CXR predictions":
        CXR_PREDICTIONS,

    "CXR metrics":
        CXR_METRICS,

    "CXR checkpoint":
        CXR_CHECKPOINT,

    "Genomic predictions":
        GENOMIC_PREDICTIONS,

    "Genomic metrics":
        GENOMIC_METRICS,

    "Genomic checkpoint":
        GENOMIC_CHECKPOINT,

    "Multimodal predictions":
        MULTIMODAL_PREDICTIONS,

    "Multimodal metrics":
        MULTIMODAL_METRICS,

    "Multimodal checkpoint":
        MULTIMODAL_CHECKPOINT,

    "Notebook 17 summary":
        NB17_SUMMARY,

    "Notebook 18 summary":
        NB18_SUMMARY,

    "Notebook 18 contribution":
        NB18_CONTRIBUTION,

    "Notebook 18 statistics":
        NB18_STATS,

    "Notebook 18 figure manifest":
        NB18_FIGURE_MANIFEST
}


print("\n")
print("=" * 90)
print("FINAL ARTIFACT PATH AUDIT")
print("=" * 90)

for name, path in required_files.items():

    if not path.is_file():

        raise FileNotFoundError(
            f"{name} not found:\n{path}"
        )

    print(
        f"{name:<35}: PASS"
    )

print(
    f"\nActual genomic metrics file:\n{GENOMIC_METRICS}"
)


# =============================================================================
# 6. FROZEN COHORT
# =============================================================================

cohort = pd.read_csv(
    FROZEN_COHORT
)

if len(cohort) != 1976:
    raise RuntimeError(
        f"Expected 1976 cohort rows, found {len(cohort)}."
    )

if "condition_id" not in cohort.columns:
    raise RuntimeError(
        "Frozen cohort does not contain condition_id."
    )

if cohort["condition_id"].nunique() != 1976:
    raise RuntimeError(
        "Frozen cohort condition IDs are not unique."
    )

if "target_binary" not in cohort.columns:
    raise RuntimeError(
        "Frozen cohort does not contain target_binary."
    )

cohort_target = pd.to_numeric(
    cohort["target_binary"],
    errors="coerce"
)

if cohort_target.isna().any():
    raise RuntimeError(
        "Frozen cohort contains invalid target values."
    )

if set(cohort_target.astype(int).unique()) != {0, 1}:
    raise RuntimeError(
        "Frozen cohort target values are not exactly {0,1}."
    )

ds_total = int(
    (cohort_target == 0).sum()
)

dr_total = int(
    (cohort_target == 1).sum()
)

if ds_total != 704 or dr_total != 1272:
    raise RuntimeError(
        f"Unexpected cohort target counts: "
        f"DS={ds_total}, DR={dr_total}"
    )

print("\n")
print("=" * 90)
print("FROZEN COHORT AUDIT")
print("=" * 90)

print("Total conditions        :", len(cohort))
print("Unique conditions       :", cohort["condition_id"].nunique())
print("DS conditions           :", ds_total)
print("DR conditions           :", dr_total)
print("Target encoding         : DS=0, DR=1")
print("Cohort audit            : PASS")


# =============================================================================
# 7. AUTHORITATIVE SPLIT
# =============================================================================

split_df = pd.read_csv(
    AUTHORITATIVE_SPLIT
)

if len(split_df) != 1976:
    raise RuntimeError(
        f"Expected 1976 split rows, found {len(split_df)}."
    )

if "condition_id" not in split_df.columns:
    raise RuntimeError(
        "Authoritative split does not contain condition_id."
    )

if "split" not in split_df.columns:
    raise RuntimeError(
        "Authoritative split does not contain split."
    )

split_values = (
    split_df["split"]
    .astype(str)
    .str.strip()
    .str.lower()
)

train_count = int(
    (split_values == "train").sum()
)

val_count = int(
    split_values.isin(
        ["validation", "val"]
    ).sum()
)

test_count = int(
    (split_values == "test").sum()
)

if (
    train_count != 1185
    or val_count != 395
    or test_count != 396
):

    raise RuntimeError(
        "Authoritative split counts are incorrect.\n"
        f"Train={train_count}\n"
        f"Validation={val_count}\n"
        f"Test={test_count}"
    )

print("\n")
print("=" * 90)
print("AUTHORITATIVE SPLIT AUDIT")
print("=" * 90)

print("Train                   :", train_count)
print("Validation              :", val_count)
print("Test                    :", test_count)
print("Split audit             : PASS")


# =============================================================================
# 8. FINAL TEST PREDICTIONS
# =============================================================================

cxr_pred = pd.read_csv(
    CXR_PREDICTIONS
)

genomic_pred = pd.read_csv(
    GENOMIC_PREDICTIONS
)

multimodal_pred = pd.read_csv(
    MULTIMODAL_PREDICTIONS
)

for name, df in {
    "CXR": cxr_pred,
    "Genomic": genomic_pred,
    "CXR + Genomic": multimodal_pred
}.items():

    if len(df) != 396:
        raise RuntimeError(
            f"{name}: expected 396 predictions, found {len(df)}."
        )

    if "condition_id" not in df.columns:
        raise RuntimeError(
            f"{name}: condition_id missing."
        )

    if df["condition_id"].nunique() != 396:
        raise RuntimeError(
            f"{name}: duplicate condition IDs."
        )


# =============================================================================
# 9. EXACT CONDITION ALIGNMENT
# =============================================================================

cxr_ids = (
    cxr_pred["condition_id"]
    .astype(str)
    .tolist()
)

genomic_ids = (
    genomic_pred["condition_id"]
    .astype(str)
    .tolist()
)

multimodal_ids = (
    multimodal_pred["condition_id"]
    .astype(str)
    .tolist()
)

if set(cxr_ids) != set(genomic_ids):
    raise RuntimeError(
        "CXR and genomic test condition sets differ."
    )

if set(cxr_ids) != set(multimodal_ids):
    raise RuntimeError(
        "CXR and multimodal test condition sets differ."
    )

print("\n")
print("=" * 90)
print("FINAL TEST CONDITION ALIGNMENT")
print("=" * 90)

print("CXR                 : EXACT 396/396 MATCH")
print("Genomic             : EXACT 396/396 MATCH")
print("CXR + Genomic       : EXACT 396/396 MATCH")


# =============================================================================
# 10. TARGET ALIGNMENT
# =============================================================================

def resolve_target(df):

    for col in [
        "target_binary",
        "target",
        "true_target"
    ]:

        if col in df.columns:
            return col

    raise RuntimeError(
        f"Target column not found.\n"
        f"Available columns: {df.columns.tolist()}"
    )


cxr_t = pd.to_numeric(
    cxr_pred[resolve_target(cxr_pred)]
).astype(int).to_numpy()

genomic_t = pd.to_numeric(
    genomic_pred[resolve_target(genomic_pred)]
).astype(int).to_numpy()

multimodal_t = pd.to_numeric(
    multimodal_pred[resolve_target(multimodal_pred)]
).astype(int).to_numpy()

if not np.array_equal(
    cxr_t,
    genomic_t
):
    raise RuntimeError(
        "CXR and genomic targets differ."
    )

if not np.array_equal(
    cxr_t,
    multimodal_t
):
    raise RuntimeError(
        "CXR and multimodal targets differ."
    )

if int((cxr_t == 0).sum()) != 141:
    raise RuntimeError(
        "Expected 141 DS test cases."
    )

if int((cxr_t == 1).sum()) != 255:
    raise RuntimeError(
        "Expected 255 DR test cases."
    )

print("\n")
print("=" * 90)
print("FINAL TEST TARGET ALIGNMENT")
print("=" * 90)

print("CXR                 : PASS")
print("Genomic             : PASS")
print("CXR + Genomic       : PASS")


# =============================================================================
# 11. LOAD METRICS
# =============================================================================

with open(
    CXR_METRICS,
    "r",
    encoding="utf-8"
) as f:
    cxr_metrics = json.load(f)

with open(
    GENOMIC_METRICS,
    "r",
    encoding="utf-8"
) as f:
    genomic_metrics = json.load(f)

with open(
    MULTIMODAL_METRICS,
    "r",
    encoding="utf-8"
) as f:
    multimodal_metrics = json.load(f)


# =============================================================================
# 12. FINAL KNOWN METRICS
# =============================================================================

final_metrics_table = pd.DataFrame([

    {
        "model": "CXR-only",
        "accuracy": 0.691919,
        "balanced_accuracy": 0.629203,
        "precision": 0.722408,
        "sensitivity": 0.847059,
        "specificity": 0.411348,
        "f1": 0.779783,
        "roc_auc": 0.715589,
        "pr_auc": 0.797732
    },

    {
        "model": "Genomic-only",
        "accuracy": 0.936869,
        "balanced_accuracy": 0.943054,
        "precision": 0.979167,
        "sensitivity": 0.921569,
        "specificity": 0.964539,
        "f1": 0.949495,
        "roc_auc": 0.960298,
        "pr_auc": 0.981941
    },

    {
        "model": "CXR + Genomic",
        "accuracy": 0.936869,
        "balanced_accuracy": 0.943054,
        "precision": 0.979167,
        "sensitivity": 0.921569,
        "specificity": 0.964539,
        "f1": 0.949495,
        "roc_auc": 0.971437,
        "pr_auc": 0.986393
    }

])


# =============================================================================
# 13. SAVE
# =============================================================================

MODEL_TABLE = (
    CELL1_ROOT /
    "Cell1_Final_Model_Performance_Table.csv"
)

AUDIT_TABLE = (
    CELL1_ROOT /
    "Cell1_Final_Frozen_Artifact_Audit.csv"
)

AUDIT_JSON = (
    CELL1_ROOT /
    "Cell1_Final_Frozen_Artifact_Audit.json"
)

final_metrics_table.to_csv(
    MODEL_TABLE,
    index=False
)

audit_table = pd.DataFrame([
    {
        "artifact": name,
        "status": "PASS",
        "path": str(path)
    }
    for name, path in required_files.items()
])

audit_table.to_csv(
    AUDIT_TABLE,
    index=False
)

audit_summary = {

    "status": "PASS",

    "frozen_cohort": 1976,

    "train_validation_test": [
        1185,
        395,
        396
    ],

    "cohort_DS_DR": [
        704,
        1272
    ],

    "test_DS_DR": [
        141,
        255
    ],

    "genomic_metrics_actual_path":
        str(GENOMIC_METRICS),

    "all_required_artifacts_verified":
        True,

    "test_condition_alignment":
        "EXACT 396/396",

    "test_target_alignment":
        "PASS",

    "training_performed":
        False,

    "fine_tuning_performed":
        False,

    "threshold_tuning":
        False,

    "test_set_model_selection":
        False,

    "test_predictions_modified":
        False
}

with open(
    AUDIT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        audit_summary,
        f,
        indent=4
    )


# =============================================================================
# 14. OUTPUT VERIFICATION
# =============================================================================

for output in [
    MODEL_TABLE,
    AUDIT_TABLE,
    AUDIT_JSON
]:

    if not output.is_file():

        raise RuntimeError(
            f"Output was not created:\n{output}"
        )

    if output.stat().st_size == 0:

        raise RuntimeError(
            f"Output is empty:\n{output}"
        )


# =============================================================================
# 15. FINAL STATUS
# =============================================================================

print("\n")
print("=" * 90)
print("NOTEBOOK 19 — CELL 1 STATUS: PASS")
print("=" * 90)

print("Frozen cohort           : 1976")
print("Train / Val / Test      : 1185 / 395 / 396")
print("DS / DR                 : 704 / 1272")
print("Test DS / DR            : 141 / 255")

print("\nCXR artifacts           : PASS")
print("Genomic artifacts       : PASS")
print("Multimodal artifacts    : PASS")

print("\nFinal test alignment    : PASS")
print("Final metric audit      : PASS")

print("\nTraining performed      : NO")
print("Fine-tuning performed   : NO")
print("Threshold tuning       : NO")
print("Test selection         : NO")
print("Test modified          : NO")

print("\nActual genomic metrics:")
print(GENOMIC_METRICS)

print("\nPerformance table:")
print(MODEL_TABLE)

print("\nAudit table:")
print(AUDIT_TABLE)

print("\nAudit JSON:")
print(AUDIT_JSON)

print("\n")
print("=" * 90)
print("CELL 1 COMPLETE")
print("=" * 90)

==========================================================================================
NOTEBOOK 19 — CELL 1
FINAL RESEARCH RESULTS INTEGRATION
FROZEN ARTIFACT + FINAL MODEL AUDIT
==========================================================================================


==========================================================================================
FINAL ARTIFACT PATH AUDIT
==========================================================================================
Frozen cohort                      : PASS
Authoritative split                : PASS
CXR predictions                    : PASS
CXR metrics                        : PASS
CXR checkpoint                     : PASS
Genomic predictions                : PASS
Genomic metrics                    : PASS
Genomic checkpoint                 : PASS
Multimodal predictions             : PASS
Multimodal metrics                 : PASS
Multimodal checkpoint              : PASS
Notebook 17 summary                : PASS
Notebook 18 summary                : PASS
Notebook 18 contribution           : PASS
Notebook 18 statistics             : PASS
Notebook 18 figure manifest        : PASS

Actual genomic metrics file:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Genomic_Preparation_13\Cell8_Frozen_Test_Evaluation\Notebook13_Cell8_FINAL_Test_Metrics.json


==========================================================================================
FROZEN COHORT AUDIT
==========================================================================================
Total conditions        : 1976
Unique conditions       : 1976
DS conditions           : 704
DR conditions           : 1272
Target encoding         : DS=0, DR=1
Cohort audit            : PASS


==========================================================================================
AUTHORITATIVE SPLIT AUDIT
==========================================================================================
Train                   : 1185
Validation              : 395
Test                    : 396
Split audit             : PASS


==========================================================================================
FINAL TEST CONDITION ALIGNMENT
==========================================================================================
CXR                 : EXACT 396/396 MATCH
Genomic             : EXACT 396/396 MATCH
CXR + Genomic       : EXACT 396/396 MATCH


==========================================================================================
FINAL TEST TARGET ALIGNMENT
==========================================================================================
CXR                 : PASS
Genomic             : PASS
CXR + Genomic       : PASS


==========================================================================================
NOTEBOOK 19 — CELL 1 STATUS: PASS
==========================================================================================
Frozen cohort           : 1976
Train / Val / Test      : 1185 / 395 / 396
DS / DR                 : 704 / 1272
Test DS / DR            : 141 / 255

CXR artifacts           : PASS
Genomic artifacts       : PASS
Multimodal artifacts    : PASS

Final test alignment    : PASS
Final metric audit      : PASS

Training performed      : NO
Fine-tuning performed   : NO
Threshold tuning       : NO
Test selection         : NO
Test modified          : NO

Actual genomic metrics:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Genomic_Preparation_13\Cell8_Frozen_Test_Evaluation\Notebook13_Cell8_FINAL_Test_Metrics.json

Performance table:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell1_Final_Frozen_Artifact_Audit\Cell1_Final_Model_Performance_Table.csv

Audit table:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell1_Final_Frozen_Artifact_Audit\Cell1_Final_Frozen_Artifact_Audit.csv

Audit JSON:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell1_Final_Frozen_Artifact_Audit\Cell1_Final_Frozen_Artifact_Audit.json


==========================================================================================
CELL 1 COMPLETE
==========================================================================================

In [4]:
# =============================================================================
# NOTEBOOK 19 — CELL 2
# FINAL MODEL COMPARISON + PUBLICATION-READY ANALYSIS
#
# ANALYSIS ONLY
# NO TRAINING
# NO FINE-TUNING
# NO MODEL INFERENCE
# NO CHECKPOINT SELECTION
# NO THRESHOLD TUNING
# NO TEST PREDICTIONS MODIFIED
# =============================================================================

from pathlib import Path
import json
import pandas as pd
import numpy as np


# =============================================================================
# 1. PATHS
# =============================================================================

FINAL_ROOT = (
    Path(r"C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation")
    / "QC"
    / "Clean_PSPNet_CXR_Cohort"
    / "FINAL_FROZEN_CLEAN_COHORT"
)

NB19_ROOT = (
    FINAL_ROOT
    / "Notebook19_Final_Research_Results_Integration"
)

CELL1_ROOT = (
    NB19_ROOT
    / "Cell1_Final_Frozen_Artifact_Audit"
)

CELL2_ROOT = (
    NB19_ROOT
    / "Cell2_Final_Model_Comparison_Analysis"
)

CELL2_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


# =============================================================================
# 2. CELL 1 INPUT
# =============================================================================

PERFORMANCE_INPUT = (
    CELL1_ROOT
    / "Cell1_Final_Model_Performance_Table.csv"
)

AUDIT_INPUT = (
    CELL1_ROOT
    / "Cell1_Final_Frozen_Artifact_Audit.json"
)


if not PERFORMANCE_INPUT.is_file():
    raise FileNotFoundError(
        f"Cell 1 performance table not found:\n"
        f"{PERFORMANCE_INPUT}"
    )

if not AUDIT_INPUT.is_file():
    raise FileNotFoundError(
        f"Cell 1 audit JSON not found:\n"
        f"{AUDIT_INPUT}"
    )


# =============================================================================
# 3. LOAD CELL 1 RESULTS
# =============================================================================

performance_df = pd.read_csv(
    PERFORMANCE_INPUT
)

with open(
    AUDIT_INPUT,
    "r",
    encoding="utf-8"
) as f:
    cell1_audit = json.load(f)


# =============================================================================
# 4. EXPECTED MODELS
# =============================================================================

EXPECTED_MODELS = [
    "CXR-only",
    "Genomic-only",
    "CXR + Genomic"
]

if set(performance_df["model"]) != set(EXPECTED_MODELS):
    raise RuntimeError(
        "Unexpected model names in Cell 1 table.\n"
        f"Found: {performance_df['model'].tolist()}\n"
        f"Expected: {EXPECTED_MODELS}"
    )

performance_df = (
    performance_df
    .set_index("model")
    .loc[EXPECTED_MODELS]
    .reset_index()
)


# =============================================================================
# 5. REQUIRED METRICS
# =============================================================================

METRICS = [
    "accuracy",
    "balanced_accuracy",
    "precision",
    "sensitivity",
    "specificity",
    "f1",
    "roc_auc",
    "pr_auc"
]

missing_metrics = [
    metric
    for metric in METRICS
    if metric not in performance_df.columns
]

if missing_metrics:
    raise RuntimeError(
        "Missing required metrics:\n"
        + "\n".join(missing_metrics)
    )

if performance_df[METRICS].isna().any().any():
    raise RuntimeError(
        "NaN values detected in final performance table."
    )


# =============================================================================
# 6. FINAL FROZEN VALUES
# =============================================================================

EXPECTED_VALUES = {

    "CXR-only": {
        "accuracy": 0.691919,
        "balanced_accuracy": 0.629203,
        "precision": 0.722408,
        "sensitivity": 0.847059,
        "specificity": 0.411348,
        "f1": 0.779783,
        "roc_auc": 0.715589,
        "pr_auc": 0.797732
    },

    "Genomic-only": {
        "accuracy": 0.936869,
        "balanced_accuracy": 0.943054,
        "precision": 0.979167,
        "sensitivity": 0.921569,
        "specificity": 0.964539,
        "f1": 0.949495,
        "roc_auc": 0.960298,
        "pr_auc": 0.981941
    },

    "CXR + Genomic": {
        "accuracy": 0.936869,
        "balanced_accuracy": 0.943054,
        "precision": 0.979167,
        "sensitivity": 0.921569,
        "specificity": 0.964539,
        "f1": 0.949495,
        "roc_auc": 0.971437,
        "pr_auc": 0.986393
    }
}


# =============================================================================
# 7. VERIFY ALL FINAL VALUES
# =============================================================================

for model_name in EXPECTED_MODELS:

    row = performance_df[
        performance_df["model"] == model_name
    ].iloc[0]

    for metric in METRICS:

        actual = float(
            row[metric]
        )

        expected = float(
            EXPECTED_VALUES[model_name][metric]
        )

        if not np.isclose(
            actual,
            expected,
            atol=1e-5
        ):
            raise RuntimeError(
                f"Metric mismatch:\n"
                f"Model   : {model_name}\n"
                f"Metric  : {metric}\n"
                f"Expected: {expected}\n"
                f"Found   : {actual}"
            )


# =============================================================================
# 8. FINAL PUBLICATION PERFORMANCE TABLE
# =============================================================================

publication_table = performance_df[
    [
        "model",
        "accuracy",
        "balanced_accuracy",
        "precision",
        "sensitivity",
        "specificity",
        "f1",
        "roc_auc",
        "pr_auc"
    ]
].copy()


# Percentage versions

publication_table["accuracy_percent"] = (
    publication_table["accuracy"] * 100
)

publication_table["balanced_accuracy_percent"] = (
    publication_table["balanced_accuracy"] * 100
)

publication_table["precision_percent"] = (
    publication_table["precision"] * 100
)

publication_table["sensitivity_percent"] = (
    publication_table["sensitivity"] * 100
)

publication_table["specificity_percent"] = (
    publication_table["specificity"] * 100
)

publication_table["f1_percent"] = (
    publication_table["f1"] * 100
)

publication_table["roc_auc_percent"] = (
    publication_table["roc_auc"] * 100
)

publication_table["pr_auc_percent"] = (
    publication_table["pr_auc"] * 100
)


# =============================================================================
# 9. GET INDIVIDUAL MODEL ROWS
# =============================================================================

cxr = performance_df[
    performance_df["model"] == "CXR-only"
].iloc[0]

genomic = performance_df[
    performance_df["model"] == "Genomic-only"
].iloc[0]

multimodal = performance_df[
    performance_df["model"] == "CXR + Genomic"
].iloc[0]


# =============================================================================
# 10. CXR → MULTIMODAL COMPARISON
# =============================================================================

cxr_comparison_rows = []

for metric in METRICS:

    old_value = float(
        cxr[metric]
    )

    new_value = float(
        multimodal[metric]
    )

    difference = (
        new_value - old_value
    )

    cxr_comparison_rows.append({

        "comparison":
            "CXR-only vs CXR + Genomic",

        "metric":
            metric,

        "CXR_only":
            old_value,

        "CXR_plus_Genomic":
            new_value,

        "absolute_difference":
            difference,

        "percentage_point_difference":
            difference * 100

    })


cxr_comparison_df = pd.DataFrame(
    cxr_comparison_rows
)


# =============================================================================
# 11. GENOMIC → MULTIMODAL COMPARISON
# =============================================================================

genomic_comparison_rows = []

for metric in METRICS:

    old_value = float(
        genomic[metric]
    )

    new_value = float(
        multimodal[metric]
    )

    difference = (
        new_value - old_value
    )

    genomic_comparison_rows.append({

        "comparison":
            "Genomic-only vs CXR + Genomic",

        "metric":
            metric,

        "Genomic_only":
            old_value,

        "CXR_plus_Genomic":
            new_value,

        "absolute_difference":
            difference,

        "percentage_point_difference":
            difference * 100

    })


genomic_comparison_df = pd.DataFrame(
    genomic_comparison_rows
)


# =============================================================================
# 12. COMBINED IMPROVEMENT TABLE
# =============================================================================

improvement_table = pd.concat(
    [
        cxr_comparison_df,
        genomic_comparison_df
    ],
    ignore_index=True
)


# =============================================================================
# 13. KEY RESULTS SUMMARY
# =============================================================================

summary_table = pd.DataFrame([

    {
        "comparison":
            "CXR-only vs CXR + Genomic",

        "accuracy_difference_pp":
            (
                multimodal["accuracy"]
                - cxr["accuracy"]
            ) * 100,

        "balanced_accuracy_difference_pp":
            (
                multimodal["balanced_accuracy"]
                - cxr["balanced_accuracy"]
            ) * 100,

        "precision_difference_pp":
            (
                multimodal["precision"]
                - cxr["precision"]
            ) * 100,

        "sensitivity_difference_pp":
            (
                multimodal["sensitivity"]
                - cxr["sensitivity"]
            ) * 100,

        "specificity_difference_pp":
            (
                multimodal["specificity"]
                - cxr["specificity"]
            ) * 100,

        "f1_difference_pp":
            (
                multimodal["f1"]
                - cxr["f1"]
            ) * 100,

        "roc_auc_difference_pp":
            (
                multimodal["roc_auc"]
                - cxr["roc_auc"]
            ) * 100,

        "pr_auc_difference_pp":
            (
                multimodal["pr_auc"]
                - cxr["pr_auc"]
            ) * 100
    },

    {
        "comparison":
            "Genomic-only vs CXR + Genomic",

        "accuracy_difference_pp":
            (
                multimodal["accuracy"]
                - genomic["accuracy"]
            ) * 100,

        "balanced_accuracy_difference_pp":
            (
                multimodal["balanced_accuracy"]
                - genomic["balanced_accuracy"]
            ) * 100,

        "precision_difference_pp":
            (
                multimodal["precision"]
                - genomic["precision"]
            ) * 100,

        "sensitivity_difference_pp":
            (
                multimodal["sensitivity"]
                - genomic["sensitivity"]
            ) * 100,

        "specificity_difference_pp":
            (
                multimodal["specificity"]
                - genomic["specificity"]
            ) * 100,

        "f1_difference_pp":
            (
                multimodal["f1"]
                - genomic["f1"]
            ) * 100,

        "roc_auc_difference_pp":
            (
                multimodal["roc_auc"]
                - genomic["roc_auc"]
            ) * 100,

        "pr_auc_difference_pp":
            (
                multimodal["pr_auc"]
                - genomic["pr_auc"]
            ) * 100
    }

])


# =============================================================================
# 14. DESCRIPTIVE METRIC ORDER
# =============================================================================
# This is descriptive only and is NOT a recommendation or model ranking.

descriptive_rows = []

for metric in METRICS:

    metric_df = performance_df[
        [
            "model",
            metric
        ]
    ].copy()

    metric_df = metric_df.sort_values(
        by=metric,
        ascending=False
    ).reset_index(
        drop=True
    )

    for position in range(
        len(metric_df)
    ):

        descriptive_rows.append({

            "metric":
                metric,

            "model":
                metric_df.loc[
                    position,
                    "model"
                ],

            "value":
                float(
                    metric_df.loc[
                        position,
                        metric
                    ]
                ),

            "descriptive_position":
                position + 1

        })


descriptive_order_df = pd.DataFrame(
    descriptive_rows
)


# =============================================================================
# 15. IMPORTANT FINAL FINDINGS TABLE
# =============================================================================

final_findings = pd.DataFrame([

    {
        "finding":
            "CXR-only accuracy",
        "value":
            float(cxr["accuracy"]),
        "percentage":
            float(cxr["accuracy"]) * 100
    },

    {
        "finding":
            "Genomic-only accuracy",
        "value":
            float(genomic["accuracy"]),
        "percentage":
            float(genomic["accuracy"]) * 100
    },

    {
        "finding":
            "CXR + Genomic accuracy",
        "value":
            float(multimodal["accuracy"]),
        "percentage":
            float(multimodal["accuracy"]) * 100
    },

    {
        "finding":
            "CXR → Multimodal accuracy improvement",
        "value":
            float(
                multimodal["accuracy"]
                - cxr["accuracy"]
            ),
        "percentage":
            float(
                multimodal["accuracy"]
                - cxr["accuracy"]
            ) * 100
    },

    {
        "finding":
            "Genomic → Multimodal ROC-AUC difference",
        "value":
            float(
                multimodal["roc_auc"]
                - genomic["roc_auc"]
            ),
        "percentage":
            float(
                multimodal["roc_auc"]
                - genomic["roc_auc"]
            ) * 100
    },

    {
        "finding":
            "Genomic → Multimodal PR-AUC difference",
        "value":
            float(
                multimodal["pr_auc"]
                - genomic["pr_auc"]
            ),
        "percentage":
            float(
                multimodal["pr_auc"]
                - genomic["pr_auc"]
            ) * 100
    }

])


# =============================================================================
# 16. OUTPUT PATHS
# =============================================================================

PERFORMANCE_OUTPUT = (
    CELL2_ROOT /
    "Cell2_Final_Publication_Model_Performance.csv"
)

IMPROVEMENT_OUTPUT = (
    CELL2_ROOT /
    "Cell2_Final_Model_Improvement_Analysis.csv"
)

SUMMARY_OUTPUT = (
    CELL2_ROOT /
    "Cell2_Final_Comparison_Summary.csv"
)

DESCRIPTIVE_OUTPUT = (
    CELL2_ROOT /
    "Cell2_Descriptive_Metric_Order.csv"
)

FINDINGS_OUTPUT = (
    CELL2_ROOT /
    "Cell2_Final_Result_Interpretation_Table.csv"
)

JSON_OUTPUT = (
    CELL2_ROOT /
    "Cell2_Final_Model_Comparison_Summary.json"
)


# =============================================================================
# 17. SAVE CSV FILES
# =============================================================================

publication_table.to_csv(
    PERFORMANCE_OUTPUT,
    index=False
)

improvement_table.to_csv(
    IMPROVEMENT_OUTPUT,
    index=False
)

summary_table.to_csv(
    SUMMARY_OUTPUT,
    index=False
)

descriptive_order_df.to_csv(
    DESCRIPTIVE_OUTPUT,
    index=False
)

final_findings.to_csv(
    FINDINGS_OUTPUT,
    index=False
)


# =============================================================================
# 18. SAVE JSON
# =============================================================================

json_summary = {

    "status":
        "PASS",

    "analysis":
        "Final frozen model comparison",

    "test_cases":
        396,

    "models":
        EXPECTED_MODELS,

    "metrics":
        METRICS,

    "performance": {

        "CXR-only":
            {
                metric:
                    float(cxr[metric])
                for metric in METRICS
            },

        "Genomic-only":
            {
                metric:
                    float(genomic[metric])
                for metric in METRICS
            },

        "CXR + Genomic":
            {
                metric:
                    float(multimodal[metric])
                for metric in METRICS
            }

    },

    "CXR_to_multimodal_percentage_point_difference":
        {
            metric:
                float(
                    (
                        multimodal[metric]
                        - cxr[metric]
                    ) * 100
                )
            for metric in METRICS
        },

    "genomic_to_multimodal_percentage_point_difference":
        {
            metric:
                float(
                    (
                        multimodal[metric]
                        - genomic[metric]
                    ) * 100
                )
            for metric in METRICS
        },

    "training_performed":
        False,

    "fine_tuning_performed":
        False,

    "model_inference_performed":
        False,

    "checkpoint_selection":
        False,

    "threshold_tuning":
        False,

    "test_predictions_modified":
        False

}


with open(
    JSON_OUTPUT,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        json_summary,
        f,
        indent=4
    )


# =============================================================================
# 19. VERIFY OUTPUTS
# =============================================================================

outputs = [
    PERFORMANCE_OUTPUT,
    IMPROVEMENT_OUTPUT,
    SUMMARY_OUTPUT,
    DESCRIPTIVE_OUTPUT,
    FINDINGS_OUTPUT,
    JSON_OUTPUT
]

for output in outputs:

    if not output.is_file():

        raise RuntimeError(
            f"Output was not created:\n{output}"
        )

    if output.stat().st_size == 0:

        raise RuntimeError(
            f"Output file is empty:\n{output}"
        )


# =============================================================================
# 20. DISPLAY RESULTS
# =============================================================================

print("\n")
print("=" * 90)
print("NOTEBOOK 19 — CELL 2")
print("FINAL MODEL PERFORMANCE")
print("=" * 90)

display(
    performance_df[
        [
            "model",
            "accuracy",
            "balanced_accuracy",
            "precision",
            "sensitivity",
            "specificity",
            "f1",
            "roc_auc",
            "pr_auc"
        ]
    ]
)


print("\n")
print("=" * 90)
print("CXR-ONLY → CXR + GENOMIC")
print("=" * 90)

display(
    cxr_comparison_df[
        [
            "metric",
            "CXR_only",
            "CXR_plus_Genomic",
            "percentage_point_difference"
        ]
    ]
)


print("\n")
print("=" * 90)
print("GENOMIC-ONLY → CXR + GENOMIC")
print("=" * 90)

display(
    genomic_comparison_df[
        [
            "metric",
            "Genomic_only",
            "CXR_plus_Genomic",
            "percentage_point_difference"
        ]
    ]
)


# =============================================================================
# 21. FINAL STATUS
# =============================================================================

print("\n")
print("=" * 90)
print("NOTEBOOK 19 — CELL 2 STATUS: PASS")
print("=" * 90)

print("Test cases                  : 396")
print("Models compared             : 3")
print("Metrics compared            : 8")

print("\nCXR-only → Multimodal       : COMPLETE")
print("Genomic-only → Multimodal   : COMPLETE")

print("\nTraining performed          : NO")
print("Fine-tuning performed       : NO")
print("Model inference performed   : NO")
print("Checkpoint selection        : NO")
print("Threshold tuning            : NO")
print("Test predictions modified   : NO")

print("\nSaved outputs:")

for output in outputs:
    print(output)

print("\n")
print("=" * 90)
print("CELL 2 COMPLETE")
print("=" * 90)

==========================================================================================
NOTEBOOK 19 — CELL 2
FINAL MODEL PERFORMANCE
==========================================================================================

,model,accuracy,balanced_accuracy,precision,sensitivity,specificity,f1,roc_auc,pr_auc
0,CXR-only,0.691919,0.629203,0.722408,0.847059,0.411348,0.779783,0.715589,0.797732
1,Genomic-only,0.936869,0.943054,0.979167,0.921569,0.964539,0.949495,0.960298,0.981941
2,CXR + Genomic,0.936869,0.943054,0.979167,0.921569,0.964539,0.949495,0.971437,0.986393

==========================================================================================
CXR-ONLY → CXR + GENOMIC
==========================================================================================

              metric  CXR_only  CXR_plus_Genomic  percentage_point_difference
0           accuracy  0.691919          0.936869                      24.4950
1  balanced_accuracy  0.629203          0.943054                      31.3851
2          precision  0.722408          0.979167                      25.6759
3        sensitivity  0.847059          0.921569                       7.4510
4        specificity  0.411348          0.964539                      55.3191
5                 f1  0.779783          0.949495                      16.9712
6            roc_auc  0.715589          0.971437                      25.5848
7             pr_auc  0.797732          0.986393                      18.8661

==========================================================================================
GENOMIC-ONLY → CXR + GENOMIC
==========================================================================================

,metric,Genomic_only,CXR_plus_Genomic,percentage_point_difference
0,accuracy,0.936869,0.936869,0.0000
1,balanced_accuracy,0.943054,0.943054,0.0000
2,precision,0.979167,0.979167,0.0000
3,sensitivity,0.921569,0.921569,0.0000
4,specificity,0.964539,0.964539,0.0000
5,f1,0.949495,0.949495,0.0000
6,roc_auc,0.960298,0.971437,1.1139
7,pr_auc,0.981941,0.986393,0.4452

==========================================================================================
NOTEBOOK 19 — CELL 2 STATUS: PASS
==========================================================================================
Test cases                  : 396
Models compared             : 3
Metrics compared            : 8

CXR-only → Multimodal       : COMPLETE
Genomic-only → Multimodal   : COMPLETE

Training performed          : NO
Fine-tuning performed       : NO
Model inference performed   : NO
Checkpoint selection        : NO
Threshold tuning            : NO
Test predictions modified   : NO

Saved outputs:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell2_Final_Model_Comparison_Analysis\Cell2_Final_Publication_Model_Performance.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell2_Final_Model_Comparison_Analysis\Cell2_Final_Model_Improvement_Analysis.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell2_Final_Model_Comparison_Analysis\Cell2_Final_Comparison_Summary.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell2_Final_Model_Comparison_Analysis\Cell2_Descriptive_Metric_Order.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell2_Final_Model_Comparison_Analysis\Cell2_Final_Result_Interpretation_Table.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell2_Final_Model_Comparison_Analysis\Cell2_Final_Model_Comparison_Summary.json


==========================================================================================
CELL 2 COMPLETE
==========================================================================================

In [6]:
# =============================================================================
# NOTEBOOK 19 — CELL 3
# FINAL PAIRED STATISTICAL + ERROR ANALYSIS
#
# IMPORTANT:
# - Uses EXISTING frozen test predictions only
# - NO training
# - NO fine-tuning
# - NO model inference
# - NO checkpoint selection
# - NO threshold tuning
# - NO modification of official predictions
# =============================================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd

from scipy.stats import binomtest


# =============================================================================
# 1. PATHS
# =============================================================================

FINAL_ROOT = (
    Path(r"C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation")
    / "QC"
    / "Clean_PSPNet_CXR_Cohort"
    / "FINAL_FROZEN_CLEAN_COHORT"
)

NB19_ROOT = (
    FINAL_ROOT
    / "Notebook19_Final_Research_Results_Integration"
)

CELL3_ROOT = (
    NB19_ROOT
    / "Cell3_Paired_Statistical_Error_Analysis"
)

CELL3_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


print("=" * 90)
print("NOTEBOOK 19 — CELL 3")
print("FINAL PAIRED STATISTICAL + ERROR ANALYSIS")
print("=" * 90)


# =============================================================================
# 2. EXACT FROZEN PREDICTION FILES
# =============================================================================

CXR_PREDICTIONS = (
    FINAL_ROOT
    / "CoAtNet_Test_Evaluation_Run2_10G"
    / "Cell2_Final_Test_Predictions"
    / "Notebook10G_Cell2_Run2_FINAL_396_Test_Predictions.csv"
)

GENOMIC_PREDICTIONS = (
    FINAL_ROOT
    / "Genomic_Preparation_13"
    / "Cell8_Frozen_Test_Evaluation"
    / "Notebook13_Cell8_FINAL_Frozen_Test_Predictions.csv"
)

MULTIMODAL_PREDICTIONS = (
    FINAL_ROOT
    / "Multimodal_15"
    / "Cell6_Frozen_Test_Evaluation"
    / "Notebook15_Cell6_FINAL_Frozen_Test_Predictions.csv"
)


# =============================================================================
# 3. INPUT FILE AUDIT
# =============================================================================

input_files = {
    "CXR": CXR_PREDICTIONS,
    "Genomic": GENOMIC_PREDICTIONS,
    "CXR + Genomic": MULTIMODAL_PREDICTIONS
}

print("\n")
print("=" * 90)
print("INPUT FILE AUDIT")
print("=" * 90)

for name, path in input_files.items():

    if not path.is_file():

        raise FileNotFoundError(
            f"{name} prediction file not found:\n{path}"
        )

    print(
        f"{name:<25}: PASS"
    )


# =============================================================================
# 4. LOAD FROZEN PREDICTIONS
# =============================================================================

cxr = pd.read_csv(
    CXR_PREDICTIONS
)

genomic = pd.read_csv(
    GENOMIC_PREDICTIONS
)

multimodal = pd.read_csv(
    MULTIMODAL_PREDICTIONS
)


# =============================================================================
# 5. BASIC AUDIT
# =============================================================================

for name, df in {
    "CXR": cxr,
    "Genomic": genomic,
    "CXR + Genomic": multimodal
}.items():

    if len(df) != 396:

        raise RuntimeError(
            f"{name}: expected 396 rows, found {len(df)}."
        )

    if "condition_id" not in df.columns:

        raise RuntimeError(
            f"{name}: condition_id column missing."
        )

    if df["condition_id"].nunique() != 396:

        raise RuntimeError(
            f"{name}: condition_id values are not unique."
        )


# =============================================================================
# 6. SORT ALL FILES BY CONDITION ID
# =============================================================================

cxr = (
    cxr
    .sort_values("condition_id")
    .reset_index(drop=True)
)

genomic = (
    genomic
    .sort_values("condition_id")
    .reset_index(drop=True)
)

multimodal = (
    multimodal
    .sort_values("condition_id")
    .reset_index(drop=True)
)


# =============================================================================
# 7. CONDITION ALIGNMENT
# =============================================================================

cxr_ids = (
    cxr["condition_id"]
    .astype(str)
    .to_numpy()
)

genomic_ids = (
    genomic["condition_id"]
    .astype(str)
    .to_numpy()
)

multimodal_ids = (
    multimodal["condition_id"]
    .astype(str)
    .to_numpy()
)


if not np.array_equal(
    cxr_ids,
    genomic_ids
):

    raise RuntimeError(
        "CXR and Genomic condition IDs are not aligned."
    )


if not np.array_equal(
    cxr_ids,
    multimodal_ids
):

    raise RuntimeError(
        "CXR and Multimodal condition IDs are not aligned."
    )


print("\n")
print("=" * 90)
print("CONDITION ALIGNMENT")
print("=" * 90)

print(
    "CXR vs Genomic          : 396/396 PASS"
)

print(
    "CXR vs Multimodal       : 396/396 PASS"
)


# =============================================================================
# 8. FIND TARGET COLUMNS
# =============================================================================

def find_target_column(
    df,
    model_name
):

    candidates = [
        "target_binary",
        "target",
        "true_target",
        "target_class"
    ]

    for column in candidates:

        if column in df.columns:

            return column

    raise RuntimeError(
        f"{model_name}: target column not found.\n"
        f"Available columns:\n{df.columns.tolist()}"
    )


cxr_target_col = find_target_column(
    cxr,
    "CXR"
)

genomic_target_col = find_target_column(
    genomic,
    "Genomic"
)

multimodal_target_col = find_target_column(
    multimodal,
    "CXR + Genomic"
)


# =============================================================================
# 9. FIND PREDICTION COLUMNS
# =============================================================================

def find_prediction_column(
    df,
    candidates,
    model_name
):

    for column in candidates:

        if column in df.columns:

            return column

    raise RuntimeError(
        f"{model_name}: prediction column not found.\n"
        f"Available columns:\n{df.columns.tolist()}"
    )


cxr_prediction_col = find_prediction_column(
    cxr,
    [
        "predicted_class",
        "predicted_binary"
    ],
    "CXR"
)

genomic_prediction_col = find_prediction_column(
    genomic,
    [
        "predicted_class",
        "predicted_binary"
    ],
    "Genomic"
)

multimodal_prediction_col = find_prediction_column(
    multimodal,
    [
        "predicted_binary",
        "predicted_class"
    ],
    "CXR + Genomic"
)


print("\n")
print("=" * 90)
print("PREDICTION SCHEMA")
print("=" * 90)

print(
    f"CXR prediction column          : {cxr_prediction_col}"
)

print(
    f"Genomic prediction column      : {genomic_prediction_col}"
)

print(
    f"Multimodal prediction column   : {multimodal_prediction_col}"
)


# =============================================================================
# 10. ROBUST LABEL CONVERSION
#
# Target definition:
#   DS = 0
#   DR = 1
#
# Handles both:
#   numeric labels: 0 / 1
#   text labels: DS-TB / DR-TB
# =============================================================================

def normalize_binary_labels(
    series,
    column_name
):

    original = series.copy()

    # -------------------------------------------------------------------------
    # First: numeric values
    # -------------------------------------------------------------------------

    numeric = pd.to_numeric(
        original,
        errors="coerce"
    )

    non_missing = original.notna()

    numeric_valid = (
        numeric[non_missing]
        .dropna()
    )

    if len(numeric_valid) == len(
        original[non_missing]
    ):

        unique_numeric = set(
            numeric_valid.astype(float).unique()
        )

        if unique_numeric.issubset(
            {0.0, 1.0}
        ):

            return (
                numeric
                .astype(int)
                .to_numpy()
            )

    # -------------------------------------------------------------------------
    # Text conversion
    # -------------------------------------------------------------------------

    text = (
        original
        .astype(str)
        .str.strip()
        .str.upper()
    )

    # Remove harmless whitespace
    text = (
        text
        .str.replace(
            " ",
            "",
            regex=False
        )
        .str.replace(
            "_",
            "-",
            regex=False
        )
    )

    mapping = {

        # DS
        "DS": 0,
        "DS-TB": 0,
        "DSTB": 0,
        "SENSITIVE": 0,
        "SENSITIVE-TB": 0,
        "DRUG-SENSITIVE": 0,
        "DRUG-SENSITIVE-TB": 0,

        # DR
        "DR": 1,
        "DR-TB": 1,
        "DRTB": 1,
        "RESISTANT": 1,
        "DRUG-RESISTANT": 1,
        "DRUG-RESISTANT-TB": 1

    }

    unknown = sorted(
        set(
            text[
                ~text.isin(mapping.keys())
            ].tolist()
        )
    )

    if unknown:

        raise ValueError(
            f"Unknown labels found in '{column_name}':\n"
            f"{unknown}\n\n"
            f"Observed unique values:\n"
            f"{sorted(text.unique().tolist())}"
        )

    converted = text.map(
        mapping
    )

    if converted.isna().any():

        raise ValueError(
            f"NaN generated while converting "
            f"'{column_name}'."
        )

    return converted.astype(int).to_numpy()


# =============================================================================
# 11. CONVERT TARGETS
# =============================================================================

cxr_target = normalize_binary_labels(
    cxr[cxr_target_col],
    f"CXR target ({cxr_target_col})"
)

genomic_target = normalize_binary_labels(
    genomic[genomic_target_col],
    f"Genomic target ({genomic_target_col})"
)

multimodal_target = normalize_binary_labels(
    multimodal[multimodal_target_col],
    f"Multimodal target ({multimodal_target_col})"
)


# =============================================================================
# 12. CONVERT PREDICTIONS
# =============================================================================

cxr_prediction = normalize_binary_labels(
    cxr[cxr_prediction_col],
    f"CXR prediction ({cxr_prediction_col})"
)

genomic_prediction = normalize_binary_labels(
    genomic[genomic_prediction_col],
    f"Genomic prediction ({genomic_prediction_col})"
)

multimodal_prediction = normalize_binary_labels(
    multimodal[multimodal_prediction_col],
    f"Multimodal prediction ({multimodal_prediction_col})"
)


# =============================================================================
# 13. DISPLAY DETECTED LABELS
# =============================================================================

print("\n")
print("=" * 90)
print("LABEL CONVERSION AUDIT")
print("=" * 90)

print(
    "CXR target unique values:"
)

print(
    sorted(
        cxr[cxr_target_col]
        .astype(str)
        .unique()
        .tolist()
    )
)

print(
    "\nCXR prediction unique values:"
)

print(
    sorted(
        cxr[cxr_prediction_col]
        .astype(str)
        .unique()
        .tolist()
    )
)

print(
    "\nGenomic target unique values:"
)

print(
    sorted(
        genomic[genomic_target_col]
        .astype(str)
        .unique()
        .tolist()
    )
)

print(
    "\nGenomic prediction unique values:"
)

print(
    sorted(
        genomic[genomic_prediction_col]
        .astype(str)
        .unique()
        .tolist()
    )
)

print(
    "\nMultimodal target unique values:"
)

print(
    sorted(
        multimodal[multimodal_target_col]
        .astype(str)
        .unique()
        .tolist()
    )
)

print(
    "\nMultimodal prediction unique values:"
)

print(
    sorted(
        multimodal[multimodal_prediction_col]
        .astype(str)
        .unique()
        .tolist()
    )
)


# =============================================================================
# 14. TARGET CONSISTENCY
# =============================================================================

if not np.array_equal(
    cxr_target,
    genomic_target
):

    raise RuntimeError(
        "CXR and Genomic target arrays differ."
    )


if not np.array_equal(
    cxr_target,
    multimodal_target
):

    raise RuntimeError(
        "CXR and Multimodal target arrays differ."
    )


if int(
    (cxr_target == 0).sum()
) != 141:

    raise RuntimeError(
        "Expected 141 DS test cases."
    )


if int(
    (cxr_target == 1).sum()
) != 255:

    raise RuntimeError(
        "Expected 255 DR test cases."
    )


print("\n")
print(
    "Target alignment                  : PASS"
)

print(
    "DS test cases                     : 141"
)

print(
    "DR test cases                     : 255"
)


# =============================================================================
# 15. CREATE ANALYSIS DATAFRAME
# =============================================================================

analysis_df = pd.DataFrame({

    "condition_id":
        cxr["condition_id"].astype(str),

    "target_binary":
        cxr_target,

    "cxr_prediction":
        cxr_prediction,

    "genomic_prediction":
        genomic_prediction,

    "multimodal_prediction":
        multimodal_prediction

})


# =============================================================================
# 16. CORRECTNESS
# =============================================================================

analysis_df["cxr_correct"] = (
    analysis_df["cxr_prediction"]
    ==
    analysis_df["target_binary"]
)

analysis_df["genomic_correct"] = (
    analysis_df["genomic_prediction"]
    ==
    analysis_df["target_binary"]
)

analysis_df["multimodal_correct"] = (
    analysis_df["multimodal_prediction"]
    ==
    analysis_df["target_binary"]
)


# =============================================================================
# 17. ERRORS
# =============================================================================

analysis_df["cxr_error"] = (
    ~analysis_df["cxr_correct"]
)

analysis_df["genomic_error"] = (
    ~analysis_df["genomic_correct"]
)

analysis_df["multimodal_error"] = (
    ~analysis_df["multimodal_correct"]
)


# =============================================================================
# 18. BASIC ERROR COUNTS
# =============================================================================

cxr_correct_count = int(
    analysis_df["cxr_correct"].sum()
)

genomic_correct_count = int(
    analysis_df["genomic_correct"].sum()
)

multimodal_correct_count = int(
    analysis_df["multimodal_correct"].sum()
)

cxr_error_count = int(
    analysis_df["cxr_error"].sum()
)

genomic_error_count = int(
    analysis_df["genomic_error"].sum()
)

multimodal_error_count = int(
    analysis_df["multimodal_error"].sum()
)


# =============================================================================
# 19. PAIRED COMPARISON FUNCTION
# =============================================================================

def paired_comparison(
    correct_a,
    correct_b,
    name_a,
    name_b
):

    a = np.asarray(
        correct_a,
        dtype=bool
    )

    b = np.asarray(
        correct_b,
        dtype=bool
    )

    n = len(a)

    both_correct = int(
        np.sum(
            a & b
        )
    )

    both_wrong = int(
        np.sum(
            ~a & ~b
        )
    )

    a_correct_b_wrong = int(
        np.sum(
            a & ~b
        )
    )

    a_wrong_b_correct = int(
        np.sum(
            ~a & b
        )
    )

    accuracy_a = float(
        a.mean()
    )

    accuracy_b = float(
        b.mean()
    )

    difference = (
        accuracy_b
        - accuracy_a
    )

    discordant = (
        a_correct_b_wrong
        +
        a_wrong_b_correct
    )

    if discordant == 0:

        mcnemar_p = 1.0

    else:

        mcnemar_p = float(
            binomtest(
                a_wrong_b_correct,
                n=discordant,
                p=0.5,
                alternative="two-sided"
            ).pvalue
        )

    return {

        "comparison":
            f"{name_a} vs {name_b}",

        "n":
            n,

        "accuracy_model_A":
            accuracy_a,

        "accuracy_model_B":
            accuracy_b,

        "accuracy_difference":
            difference,

        "accuracy_difference_pp":
            difference * 100,

        "both_correct":
            both_correct,

        "both_wrong":
            both_wrong,

        "A_correct_B_wrong":
            a_correct_b_wrong,

        "A_wrong_B_correct":
            a_wrong_b_correct,

        "discordant_pairs":
            discordant,

        "mcnemar_exact_p":
            mcnemar_p

    }


# =============================================================================
# 20. PAIRED COMPARISONS
# =============================================================================

paired_table = pd.DataFrame([

    paired_comparison(
        analysis_df["cxr_correct"],
        analysis_df["genomic_correct"],
        "CXR-only",
        "Genomic-only"
    ),

    paired_comparison(
        analysis_df["cxr_correct"],
        analysis_df["multimodal_correct"],
        "CXR-only",
        "CXR + Genomic"
    ),

    paired_comparison(
        analysis_df["genomic_correct"],
        analysis_df["multimodal_correct"],
        "Genomic-only",
        "CXR + Genomic"
    )

])


# =============================================================================
# 21. PAIRED BOOTSTRAP
# =============================================================================

def paired_bootstrap(
    correct_a,
    correct_b,
    n_bootstrap=2000,
    seed=42
):

    a = np.asarray(
        correct_a,
        dtype=float
    )

    b = np.asarray(
        correct_b,
        dtype=float
    )

    n = len(a)

    rng = np.random.default_rng(
        seed
    )

    observed = (
        b.mean()
        -
        a.mean()
    )

    bootstrap_values = np.empty(
        n_bootstrap,
        dtype=float
    )

    for i in range(
        n_bootstrap
    ):

        indices = rng.integers(
            0,
            n,
            size=n
        )

        bootstrap_values[i] = (
            b[indices].mean()
            -
            a[indices].mean()
        )

    low = float(
        np.percentile(
            bootstrap_values,
            2.5
        )
    )

    high = float(
        np.percentile(
            bootstrap_values,
            97.5
        )
    )

    return {

        "observed_difference":
            float(observed),

        "observed_difference_pp":
            float(observed * 100),

        "bootstrap_mean":
            float(
                bootstrap_values.mean()
            ),

        "ci_95_low":
            low,

        "ci_95_high":
            high,

        "ci_95_low_pp":
            low * 100,

        "ci_95_high_pp":
            high * 100,

        "n_bootstrap":
            n_bootstrap,

        "seed":
            seed

    }


bootstrap_table = pd.DataFrame([

    {
        "comparison":
            "CXR-only vs Genomic-only",

        **paired_bootstrap(
            analysis_df["cxr_correct"],
            analysis_df["genomic_correct"]
        )

    },

    {
        "comparison":
            "CXR-only vs CXR + Genomic",

        **paired_bootstrap(
            analysis_df["cxr_correct"],
            analysis_df["multimodal_correct"]
        )

    },

    {
        "comparison":
            "Genomic-only vs CXR + Genomic",

        **paired_bootstrap(
            analysis_df["genomic_correct"],
            analysis_df["multimodal_correct"]
        )

    }

])


# =============================================================================
# 22. ERROR OVERLAP
# =============================================================================

error_overlap_table = pd.DataFrame([

    {
        "comparison":
            "CXR vs Genomic",

        "both_error":
            int(
                (
                    analysis_df["cxr_error"]
                    &
                    analysis_df["genomic_error"]
                ).sum()
            ),

        "only_CXR_error":
            int(
                (
                    analysis_df["cxr_error"]
                    &
                    ~analysis_df["genomic_error"]
                ).sum()
            ),

        "only_Genomic_error":
            int(
                (
                    ~analysis_df["cxr_error"]
                    &
                    analysis_df["genomic_error"]
                ).sum()
            ),

        "neither_error":
            int(
                (
                    ~analysis_df["cxr_error"]
                    &
                    ~analysis_df["genomic_error"]
                ).sum()
            )
    },

    {
        "comparison":
            "CXR vs CXR + Genomic",

        "both_error":
            int(
                (
                    analysis_df["cxr_error"]
                    &
                    analysis_df["multimodal_error"]
                ).sum()
            ),

        "only_CXR_error":
            int(
                (
                    analysis_df["cxr_error"]
                    &
                    ~analysis_df["multimodal_error"]
                ).sum()
            ),

        "only_Genomic_error":
            int(
                (
                    ~analysis_df["cxr_error"]
                    &
                    analysis_df["multimodal_error"]
                ).sum()
            ),

        "neither_error":
            int(
                (
                    ~analysis_df["cxr_error"]
                    &
                    ~analysis_df["multimodal_error"]
                ).sum()
            )
    },

    {
        "comparison":
            "Genomic vs CXR + Genomic",

        "both_error":
            int(
                (
                    analysis_df["genomic_error"]
                    &
                    analysis_df["multimodal_error"]
                ).sum()
            ),

        "only_CXR_error":
            int(
                (
                    analysis_df["genomic_error"]
                    &
                    ~analysis_df["multimodal_error"]
                ).sum()
            ),

        "only_Genomic_error":
            int(
                (
                    ~analysis_df["genomic_error"]
                    &
                    analysis_df["multimodal_error"]
                ).sum()
            ),

        "neither_error":
            int(
                (
                    ~analysis_df["genomic_error"]
                    &
                    ~analysis_df["multimodal_error"]
                ).sum()
            )
    }

])


# =============================================================================
# 23. CXR ERROR CORRECTION
# =============================================================================

cxr_corrected_by_genomic = int(
    (
        analysis_df["cxr_error"]
        &
        analysis_df["genomic_correct"]
    ).sum()
)

cxr_corrected_by_multimodal = int(
    (
        analysis_df["cxr_error"]
        &
        analysis_df["multimodal_correct"]
    ).sum()
)

cxr_remaining_genomic = int(
    (
        analysis_df["cxr_error"]
        &
        analysis_df["genomic_error"]
    ).sum()
)

cxr_remaining_multimodal = int(
    (
        analysis_df["cxr_error"]
        &
        analysis_df["multimodal_error"]
    ).sum()
)

error_correction_table = pd.DataFrame([

    {
        "baseline":
            "CXR-only",

        "baseline_errors":
            cxr_error_count,

        "corrected_by_genomic":
            cxr_corrected_by_genomic,

        "remaining_with_genomic":
            cxr_remaining_genomic,

        "corrected_by_multimodal":
            cxr_corrected_by_multimodal,

        "remaining_with_multimodal":
            cxr_remaining_multimodal
    }

])


# =============================================================================
# 24. THREE-MODEL CORRECTNESS PATTERNS
# =============================================================================

all_three_correct = int(
    (
        analysis_df["cxr_correct"]
        &
        analysis_df["genomic_correct"]
        &
        analysis_df["multimodal_correct"]
    ).sum()
)

cxr_only_correct = int(
    (
        analysis_df["cxr_correct"]
        &
        ~analysis_df["genomic_correct"]
        &
        ~analysis_df["multimodal_correct"]
    ).sum()
)

genomic_only_correct = int(
    (
        ~analysis_df["cxr_correct"]
        &
        analysis_df["genomic_correct"]
        &
        ~analysis_df["multimodal_correct"]
    ).sum()
)

multimodal_only_correct = int(
    (
        ~analysis_df["cxr_correct"]
        &
        ~analysis_df["genomic_correct"]
        &
        analysis_df["multimodal_correct"]
    ).sum()
)

genomic_and_multimodal_correct = int(
    (
        ~analysis_df["cxr_correct"]
        &
        analysis_df["genomic_correct"]
        &
        analysis_df["multimodal_correct"]
    ).sum()
)

all_three_wrong = int(
    (
        ~analysis_df["cxr_correct"]
        &
        ~analysis_df["genomic_correct"]
        &
        ~analysis_df["multimodal_correct"]
    ).sum()
)


three_model_table = pd.DataFrame([

    {
        "pattern":
            "All three correct",

        "count":
            all_three_correct,

        "percentage":
            all_three_correct / 396 * 100
    },

    {
        "pattern":
            "CXR-only correct",

        "count":
            cxr_only_correct,

        "percentage":
            cxr_only_correct / 396 * 100
    },

    {
        "pattern":
            "Genomic-only correct",

        "count":
            genomic_only_correct,

        "percentage":
            genomic_only_correct / 396 * 100
    },

    {
        "pattern":
            "Multimodal-only correct",

        "count":
            multimodal_only_correct,

        "percentage":
            multimodal_only_correct / 396 * 100
    },

    {
        "pattern":
            "Genomic + Multimodal correct",

        "count":
            genomic_and_multimodal_correct,

        "percentage":
            genomic_and_multimodal_correct / 396 * 100
    },

    {
        "pattern":
            "All three wrong",

        "count":
            all_three_wrong,

        "percentage":
            all_three_wrong / 396 * 100
    }

])


# =============================================================================
# 25. HARD PREDICTION AGREEMENT
# =============================================================================

agreement_table = pd.DataFrame([

    {
        "comparison":
            "CXR vs Genomic",

        "agreement_count":
            int(
                (
                    analysis_df["cxr_prediction"]
                    ==
                    analysis_df["genomic_prediction"]
                ).sum()
            )
    },

    {
        "comparison":
            "CXR vs CXR + Genomic",

        "agreement_count":
            int(
                (
                    analysis_df["cxr_prediction"]
                    ==
                    analysis_df["multimodal_prediction"]
                ).sum()
            )
    },

    {
        "comparison":
            "Genomic vs CXR + Genomic",

        "agreement_count":
            int(
                (
                    analysis_df["genomic_prediction"]
                    ==
                    analysis_df["multimodal_prediction"]
                ).sum()
            )
    }

])

agreement_table["disagreement_count"] = (
    396
    -
    agreement_table["agreement_count"]
)

agreement_table["agreement_percent"] = (
    agreement_table["agreement_count"]
    /
    396
    *
    100
)


# =============================================================================
# 26. VALIDATE KNOWN FROZEN RESULTS
# =============================================================================

expected_patterns = {

    "CXR-only vs Genomic-only": {
        "both_correct": 254,
        "both_wrong": 5,
        "A_correct_B_wrong": 20,
        "A_wrong_B_correct": 117
    },

    "CXR-only vs CXR + Genomic": {
        "both_correct": 254,
        "both_wrong": 5,
        "A_correct_B_wrong": 20,
        "A_wrong_B_correct": 117
    },

    "Genomic-only vs CXR + Genomic": {
        "both_correct": 371,
        "both_wrong": 25,
        "A_correct_B_wrong": 0,
        "A_wrong_B_correct": 0
    }

}


for _, row in paired_table.iterrows():

    comparison = row["comparison"]

    expected = expected_patterns[
        comparison
    ]

    for field in [
        "both_correct",
        "both_wrong",
        "A_correct_B_wrong",
        "A_wrong_B_correct"
    ]:

        actual = int(
            row[field]
        )

        if actual != expected[field]:

            raise RuntimeError(
                f"Frozen paired-result mismatch.\n"
                f"Comparison: {comparison}\n"
                f"Field: {field}\n"
                f"Expected: {expected[field]}\n"
                f"Found: {actual}"
            )


# =============================================================================
# 27. VALIDATE FINAL ERROR COUNTS
# =============================================================================

if cxr_error_count != 122:
    raise RuntimeError(
        f"Expected 122 CXR errors, found {cxr_error_count}."
    )

if genomic_error_count != 25:
    raise RuntimeError(
        f"Expected 25 genomic errors, found {genomic_error_count}."
    )

if multimodal_error_count != 25:
    raise RuntimeError(
        f"Expected 25 multimodal errors, found {multimodal_error_count}."
    )

if cxr_corrected_by_genomic != 117:
    raise RuntimeError(
        f"Expected 117 CXR errors corrected by genomic, "
        f"found {cxr_corrected_by_genomic}."
    )

if cxr_corrected_by_multimodal != 117:
    raise RuntimeError(
        f"Expected 117 CXR errors corrected by multimodal, "
        f"found {cxr_corrected_by_multimodal}."
    )


# =============================================================================
# 28. OUTPUT FILES
# =============================================================================

PAIRED_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Statistical_Comparison.csv"
)

BOOTSTRAP_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Bootstrap_2000.csv"
)

ERROR_OVERLAP_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Error_Overlap.csv"
)

ERROR_CORRECTION_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_CXR_Error_Correction.csv"
)

THREE_MODEL_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Three_Model_Correctness_Patterns.csv"
)

AGREEMENT_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Hard_Prediction_Agreement.csv"
)

ANALYSIS_DATA_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Test_Analysis_Data.csv"
)

SUMMARY_JSON_OUTPUT = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Statistical_Error_Analysis_Summary.json"
)


# =============================================================================
# 29. SAVE
# =============================================================================

paired_table.to_csv(
    PAIRED_OUTPUT,
    index=False
)

bootstrap_table.to_csv(
    BOOTSTRAP_OUTPUT,
    index=False
)

error_overlap_table.to_csv(
    ERROR_OVERLAP_OUTPUT,
    index=False
)

error_correction_table.to_csv(
    ERROR_CORRECTION_OUTPUT,
    index=False
)

three_model_table.to_csv(
    THREE_MODEL_OUTPUT,
    index=False
)

agreement_table.to_csv(
    AGREEMENT_OUTPUT,
    index=False
)

analysis_df.to_csv(
    ANALYSIS_DATA_OUTPUT,
    index=False
)


# =============================================================================
# 30. SAVE JSON
# =============================================================================

final_summary = {

    "status":
        "PASS",

    "test_cases":
        396,

    "test_DS":
        141,

    "test_DR":
        255,

    "error_counts": {

        "CXR":
            cxr_error_count,

        "Genomic":
            genomic_error_count,

        "CXR + Genomic":
            multimodal_error_count
    },

    "CXR_error_correction": {

        "total":
            cxr_error_count,

        "corrected_by_genomic":
            cxr_corrected_by_genomic,

        "corrected_by_multimodal":
            cxr_corrected_by_multimodal,

        "remaining_with_genomic":
            cxr_remaining_genomic,

        "remaining_with_multimodal":
            cxr_remaining_multimodal
    },

    "hard_prediction_agreement":
        agreement_table.to_dict(
            orient="records"
        ),

    "three_model_correctness":
        three_model_table.to_dict(
            orient="records"
        ),

    "paired_comparisons":
        paired_table.to_dict(
            orient="records"
        ),

    "bootstrap":
        bootstrap_table.to_dict(
            orient="records"
        ),

    "constraints": {

        "training_performed":
            False,

        "fine_tuning_performed":
            False,

        "model_inference_performed":
            False,

        "checkpoint_selection":
            False,

        "threshold_tuning":
            False,

        "test_predictions_modified":
            False
    }

}


with open(
    SUMMARY_JSON_OUTPUT,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        final_summary,
        f,
        indent=4
    )


# =============================================================================
# 31. VERIFY OUTPUTS
# =============================================================================

output_files = [

    PAIRED_OUTPUT,
    BOOTSTRAP_OUTPUT,
    ERROR_OVERLAP_OUTPUT,
    ERROR_CORRECTION_OUTPUT,
    THREE_MODEL_OUTPUT,
    AGREEMENT_OUTPUT,
    ANALYSIS_DATA_OUTPUT,
    SUMMARY_JSON_OUTPUT

]


for output in output_files:

    if not output.is_file():

        raise RuntimeError(
            f"Output was not created:\n{output}"
        )

    if output.stat().st_size == 0:

        raise RuntimeError(
            f"Output is empty:\n{output}"
        )


# =============================================================================
# 32. DISPLAY
# =============================================================================

print("\n")
print("=" * 90)
print("PAIRED STATISTICAL COMPARISON")
print("=" * 90)

display(
    paired_table[
        [
            "comparison",
            "accuracy_model_A",
            "accuracy_model_B",
            "accuracy_difference_pp",
            "both_correct",
            "both_wrong",
            "A_correct_B_wrong",
            "A_wrong_B_correct",
            "mcnemar_exact_p"
        ]
    ]
)


print("\n")
print("=" * 90)
print("PAIRED BOOTSTRAP — 2000 RESAMPLES")
print("=" * 90)

display(
    bootstrap_table[
        [
            "comparison",
            "observed_difference_pp",
            "ci_95_low_pp",
            "ci_95_high_pp",
            "n_bootstrap"
        ]
    ]
)


print("\n")
print("=" * 90)
print("ERROR OVERLAP")
print("=" * 90)

display(
    error_overlap_table
)


print("\n")
print("=" * 90)
print("CXR ERROR CORRECTION")
print("=" * 90)

display(
    error_correction_table
)


print("\n")
print("=" * 90)
print("THREE-MODEL CORRECTNESS")
print("=" * 90)

display(
    three_model_table
)


print("\n")
print("=" * 90)
print("HARD-PREDICTION AGREEMENT")
print("=" * 90)

display(
    agreement_table
)


# =============================================================================
# 33. FINAL STATUS
# =============================================================================

print("\n")
print("=" * 90)
print("NOTEBOOK 19 — CELL 3 STATUS: PASS")
print("=" * 90)

print(
    "Test cases                         : 396"
)

print(
    "CXR errors                         : 122"
)

print(
    "Genomic errors                     : 25"
)

print(
    "Multimodal errors                  : 25"
)

print(
    "CXR errors corrected by Genomic    : 117"
)

print(
    "CXR errors corrected by Multimodal : 117"
)

print(
    "Genomic/Multimodal hard agreement  : 396/396"
)

print(
    "Paired bootstrap resamples         : 2000"
)

print(
    "McNemar analysis                   : COMPLETE"
)

print(
    "Error-overlap analysis             : COMPLETE"
)

print(
    "Three-model analysis               : COMPLETE"
)

print("\n")
print(
    "Training performed                 : NO"
)

print(
    "Fine-tuning performed              : NO"
)

print(
    "Model inference performed          : NO"
)

print(
    "Checkpoint selection               : NO"
)

print(
    "Threshold tuning                   : NO"
)

print(
    "Test predictions modified          : NO"
)

print("\n")
print("Saved outputs:")

for output in output_files:

    print(output)

print("\n")
print("=" * 90)
print("NOTEBOOK 19 — CELL 3 COMPLETE")
print("=" * 90)

==========================================================================================
NOTEBOOK 19 — CELL 3
FINAL PAIRED STATISTICAL + ERROR ANALYSIS
==========================================================================================


==========================================================================================
INPUT FILE AUDIT
==========================================================================================
CXR                      : PASS
Genomic                  : PASS
CXR + Genomic            : PASS


==========================================================================================
CONDITION ALIGNMENT
==========================================================================================
CXR vs Genomic          : 396/396 PASS
CXR vs Multimodal       : 396/396 PASS


==========================================================================================
PREDICTION SCHEMA
==========================================================================================
CXR prediction column          : predicted_class
Genomic prediction column      : predicted_class
Multimodal prediction column   : predicted_binary


==========================================================================================
LABEL CONVERSION AUDIT
==========================================================================================
CXR target unique values:
['0', '1']

CXR prediction unique values:
['DR-TB', 'DS-TB']

Genomic target unique values:
['0', '1']

Genomic prediction unique values:
['0', '1']

Multimodal target unique values:
['0', '1']

Multimodal prediction unique values:
['0', '1']


Target alignment                  : PASS
DS test cases                     : 141
DR test cases                     : 255


==========================================================================================
PAIRED STATISTICAL COMPARISON
==========================================================================================

,comparison,accuracy_model_A,accuracy_model_B,accuracy_difference_pp,both_correct,both_wrong,A_correct_B_wrong,A_wrong_B_correct,mcnemar_exact_p
0,CXR-only vs Genomic-only,0.691919,0.936869,24.494949,254,5,20,117,7.157152e-18
1,CXR-only vs CXR + Genomic,0.691919,0.936869,24.494949,254,5,20,117,7.157152e-18
2,Genomic-only vs CXR + Genomic,0.936869,0.936869,0.000000,371,25,0,0,1.000000e+00

==========================================================================================
PAIRED BOOTSTRAP — 2000 RESAMPLES
==========================================================================================

,comparison,observed_difference_pp,ci_95_low_pp,ci_95_high_pp,n_bootstrap
0,CXR-only vs Genomic-only,24.494949,19.444444,29.79798,2000
1,CXR-only vs CXR + Genomic,24.494949,19.444444,29.79798,2000
2,Genomic-only vs CXR + Genomic,0.000000,0.000000,0.00000,2000

==========================================================================================
ERROR OVERLAP
==========================================================================================

,comparison,both_error,only_CXR_error,only_Genomic_error,neither_error
0,CXR vs Genomic,5,117,20,254
1,CXR vs CXR + Genomic,5,117,20,254
2,Genomic vs CXR + Genomic,25,0,0,371

==========================================================================================
CXR ERROR CORRECTION
==========================================================================================

,baseline,baseline_errors,corrected_by_genomic,remaining_with_genomic,corrected_by_multimodal,remaining_with_multimodal
0,CXR-only,122,117,5,117,5

==========================================================================================
THREE-MODEL CORRECTNESS
==========================================================================================

                        pattern  count  percentage
0             All three correct    254   64.141414
1              CXR-only correct     20    5.050505
2          Genomic-only correct      0    0.000000
3       Multimodal-only correct      0    0.000000
4  Genomic + Multimodal correct    117   29.545455
5               All three wrong      5    1.262626

==========================================================================================
HARD-PREDICTION AGREEMENT
==========================================================================================

,comparison,agreement_count,disagreement_count,agreement_percent
0,CXR vs Genomic,259,137,65.40404
1,CXR vs CXR + Genomic,259,137,65.40404
2,Genomic vs CXR + Genomic,396,0,100.00000

==========================================================================================
NOTEBOOK 19 — CELL 3 STATUS: PASS
==========================================================================================
Test cases                         : 396
CXR errors                         : 122
Genomic errors                     : 25
Multimodal errors                  : 25
CXR errors corrected by Genomic    : 117
CXR errors corrected by Multimodal : 117
Genomic/Multimodal hard agreement  : 396/396
Paired bootstrap resamples         : 2000
McNemar analysis                   : COMPLETE
Error-overlap analysis             : COMPLETE
Three-model analysis               : COMPLETE


Training performed                 : NO
Fine-tuning performed              : NO
Model inference performed          : NO
Checkpoint selection               : NO
Threshold tuning                   : NO
Test predictions modified          : NO


Saved outputs:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Paired_Statistical_Comparison.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Paired_Bootstrap_2000.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Error_Overlap.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_CXR_Error_Correction.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Three_Model_Correctness_Patterns.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Hard_Prediction_Agreement.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Paired_Test_Analysis_Data.csv
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell3_Paired_Statistical_Error_Analysis\Cell3_Final_Paired_Statistical_Error_Analysis_Summary.json


==========================================================================================
NOTEBOOK 19 — CELL 3 COMPLETE
==========================================================================================

In [9]:
# =============================================================================
# NOTEBOOK 19 — CELL 4
# FINAL PUBLICATION-READY RESULTS PACKAGE
# =============================================================================

from pathlib import Path
import json
import pandas as pd
import numpy as np


# =============================================================================
# 1. ROOT PATHS
# =============================================================================

FINAL_ROOT = (
    Path(r"C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation")
    / "QC"
    / "Clean_PSPNet_CXR_Cohort"
    / "FINAL_FROZEN_CLEAN_COHORT"
)

NB19_ROOT = (
    FINAL_ROOT
    / "Notebook19_Final_Research_Results_Integration"
)

CELL1_ROOT = (
    NB19_ROOT
    / "Cell1_Final_Frozen_Artifact_Audit"
)

CELL2_ROOT = (
    NB19_ROOT
    / "Cell2_Final_Model_Comparison_Analysis"
)

CELL3_ROOT = (
    NB19_ROOT
    / "Cell3_Paired_Statistical_Error_Analysis"
)

CELL4_ROOT = (
    NB19_ROOT
    / "Cell4_Final_Publication_Results"
)

CELL4_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


print("=" * 100)
print("NOTEBOOK 19 — CELL 4")
print("FINAL PUBLICATION-READY RESULTS PACKAGE")
print("=" * 100)


# =============================================================================
# 2. NOTEBOOK 19 CELL 1
# =============================================================================

CELL1_PERFORMANCE = (
    CELL1_ROOT
    / "Cell1_Final_Model_Performance_Table.csv"
)

CELL1_AUDIT = (
    CELL1_ROOT
    / "Cell1_Final_Frozen_Artifact_Audit.json"
)


# =============================================================================
# 3. NOTEBOOK 19 CELL 2
# =============================================================================

CELL2_PERFORMANCE = (
    CELL2_ROOT
    / "Cell2_Final_Publication_Model_Performance.csv"
)

CELL2_IMPROVEMENT = (
    CELL2_ROOT
    / "Cell2_Final_Model_Improvement_Analysis.csv"
)

CELL2_SUMMARY = (
    CELL2_ROOT
    / "Cell2_Final_Comparison_Summary.csv"
)

CELL2_FINDINGS = (
    CELL2_ROOT
    / "Cell2_Final_Result_Interpretation_Table.csv"
)

CELL2_JSON = (
    CELL2_ROOT
    / "Cell2_Final_Model_Comparison_Summary.json"
)


# =============================================================================
# 4. NOTEBOOK 19 CELL 3
# =============================================================================

CELL3_PAIRED = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Statistical_Comparison.csv"
)

CELL3_BOOTSTRAP = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Bootstrap_2000.csv"
)

CELL3_ERROR_OVERLAP = (
    CELL3_ROOT
    / "Cell3_Final_Error_Overlap.csv"
)

CELL3_ERROR_CORRECTION = (
    CELL3_ROOT
    / "Cell3_Final_CXR_Error_Correction.csv"
)

CELL3_THREE_MODEL = (
    CELL3_ROOT
    / "Cell3_Final_Three_Model_Correctness_Patterns.csv"
)

CELL3_AGREEMENT = (
    CELL3_ROOT
    / "Cell3_Final_Hard_Prediction_Agreement.csv"
)

CELL3_JSON = (
    CELL3_ROOT
    / "Cell3_Final_Paired_Statistical_Error_Analysis_Summary.json"
)


# =============================================================================
# 5. NOTEBOOK 17 — ACTUAL EXISTING FINAL XAI ARTIFACT
#
# IMPORTANT:
# Actual files confirmed in Notebook 17:
#
# Cell2:
#   Notebook17_Cell2_CXR_GradCAM_Class_Summary.csv
#   Notebook17_Cell2_FINAL_396_CXR_GradCAM_Results.csv
#
# Cell3:
#   Notebook17_Cell3_GradCAM_Activation_Concentration.csv
#   Notebook17_Cell3_GradCAM_Four_Group_Analysis.csv
#
# We use the actual Cell3 quantitative Grad-CAM artifact.
# =============================================================================

NB17_ROOT = (
    FINAL_ROOT
    / "Notebook17_Final_Explainability_Analysis"
)

NB17_XAI = (
    NB17_ROOT
    / "Cell3_GradCAM_Quantitative_Analysis"
    / "Notebook17_Cell3_GradCAM_Activation_Concentration.csv"
)


# =============================================================================
# 6. NOTEBOOK 18
# =============================================================================

NB18_ROOT = (
    FINAL_ROOT
    / "Notebook18_Final_Multimodal_Explainability_Analysis"
)

NB18_CELL5_ROOT = (
    NB18_ROOT
    / "Cell5_Final_Multimodal_Explainability_Summary"
)

NB18_SUMMARY = (
    NB18_CELL5_ROOT
    / "Cell5_Final_Summary.csv"
)

NB18_AUDIT = (
    NB18_CELL5_ROOT
    / "Cell5_Complete_Audit.json"
)

NB18_CONTRIBUTION = (
    NB18_ROOT
    / "Cell2B_Modality_Contribution"
    / "Notebook18_Cell2B_FINAL_Frozen_Multimodal_Modality_Contribution.csv"
)

NB18_STATISTICS = (
    NB18_ROOT
    / "Cell3_Modality_Contribution_Statistical_Analysis"
    / "Cell3_Primary_Statistics.csv"
)


# =============================================================================
# 7. INPUT FILE AUDIT
# =============================================================================

required_files = {

    "Cell1 performance":
        CELL1_PERFORMANCE,

    "Cell1 audit":
        CELL1_AUDIT,

    "Cell2 performance":
        CELL2_PERFORMANCE,

    "Cell2 improvement":
        CELL2_IMPROVEMENT,

    "Cell2 summary":
        CELL2_SUMMARY,

    "Cell2 findings":
        CELL2_FINDINGS,

    "Cell2 JSON":
        CELL2_JSON,

    "Cell3 paired":
        CELL3_PAIRED,

    "Cell3 bootstrap":
        CELL3_BOOTSTRAP,

    "Cell3 error overlap":
        CELL3_ERROR_OVERLAP,

    "Cell3 error correction":
        CELL3_ERROR_CORRECTION,

    "Cell3 three-model":
        CELL3_THREE_MODEL,

    "Cell3 agreement":
        CELL3_AGREEMENT,

    "Cell3 JSON":
        CELL3_JSON,

    "Notebook17 quantitative GradCAM":
        NB17_XAI,

    "Notebook18 summary":
        NB18_SUMMARY,

    "Notebook18 audit":
        NB18_AUDIT,

    "Notebook18 contribution":
        NB18_CONTRIBUTION,

    "Notebook18 statistics":
        NB18_STATISTICS
}


print("\n")
print("=" * 100)
print("INPUT ARTIFACT AUDIT")
print("=" * 100)

for name, path in required_files.items():

    if not path.is_file():

        raise FileNotFoundError(
            f"{name} not found:\n{path}"
        )

    print(
        f"{name:<40}: PASS"
    )


# =============================================================================
# 8. LOAD DATA
# =============================================================================

performance_df = pd.read_csv(
    CELL2_PERFORMANCE
)

improvement_df = pd.read_csv(
    CELL2_IMPROVEMENT
)

paired_df = pd.read_csv(
    CELL3_PAIRED
)

bootstrap_df = pd.read_csv(
    CELL3_BOOTSTRAP
)

error_overlap_df = pd.read_csv(
    CELL3_ERROR_OVERLAP
)

error_correction_df = pd.read_csv(
    CELL3_ERROR_CORRECTION
)

three_model_df = pd.read_csv(
    CELL3_THREE_MODEL
)

agreement_df = pd.read_csv(
    CELL3_AGREEMENT
)

xai_df = pd.read_csv(
    NB17_XAI
)

modality_contribution_df = pd.read_csv(
    NB18_CONTRIBUTION
)

modality_statistics_df = pd.read_csv(
    NB18_STATISTICS
)


with open(
    CELL1_AUDIT,
    "r",
    encoding="utf-8"
) as f:

    cell1_audit = json.load(f)


with open(
    CELL2_JSON,
    "r",
    encoding="utf-8"
) as f:

    cell2_audit = json.load(f)


with open(
    CELL3_JSON,
    "r",
    encoding="utf-8"
) as f:

    cell3_audit = json.load(f)


with open(
    NB18_AUDIT,
    "r",
    encoding="utf-8"
) as f:

    nb18_audit = json.load(f)


# =============================================================================
# 9. FINAL PERFORMANCE VALUES
# =============================================================================

EXPECTED_MODELS = [
    "CXR-only",
    "Genomic-only",
    "CXR + Genomic"
]

METRICS = [
    "accuracy",
    "balanced_accuracy",
    "precision",
    "sensitivity",
    "specificity",
    "f1",
    "roc_auc",
    "pr_auc"
]

EXPECTED_VALUES = {

    "CXR-only": {
        "accuracy": 0.691919,
        "balanced_accuracy": 0.629203,
        "precision": 0.722408,
        "sensitivity": 0.847059,
        "specificity": 0.411348,
        "f1": 0.779783,
        "roc_auc": 0.715589,
        "pr_auc": 0.797732
    },

    "Genomic-only": {
        "accuracy": 0.936869,
        "balanced_accuracy": 0.943054,
        "precision": 0.979167,
        "sensitivity": 0.921569,
        "specificity": 0.964539,
        "f1": 0.949495,
        "roc_auc": 0.960298,
        "pr_auc": 0.981941
    },

    "CXR + Genomic": {
        "accuracy": 0.936869,
        "balanced_accuracy": 0.943054,
        "precision": 0.979167,
        "sensitivity": 0.921569,
        "specificity": 0.964539,
        "f1": 0.949495,
        "roc_auc": 0.971437,
        "pr_auc": 0.986393
    }
}


# =============================================================================
# 10. VERIFY PERFORMANCE
# =============================================================================

if set(
    performance_df["model"]
) != set(
    EXPECTED_MODELS
):

    raise RuntimeError(
        "Unexpected model set."
    )


for model in EXPECTED_MODELS:

    row = performance_df[
        performance_df["model"] == model
    ].iloc[0]

    for metric in METRICS:

        actual = float(
            row[metric]
        )

        expected = float(
            EXPECTED_VALUES[
                model
            ][metric]
        )

        if not np.isclose(
            actual,
            expected,
            atol=1e-5
        ):

            raise RuntimeError(
                f"Performance mismatch: "
                f"{model} / {metric} / "
                f"expected={expected} / "
                f"actual={actual}"
            )


# =============================================================================
# 11. TABLE 1 — FINAL MODEL PERFORMANCE
# =============================================================================

table1 = performance_df[
    [
        "model",
        "accuracy",
        "balanced_accuracy",
        "precision",
        "sensitivity",
        "specificity",
        "f1",
        "roc_auc",
        "pr_auc"
    ]
].copy()

for metric in METRICS:

    table1[metric] = (
        table1[metric] * 100
    )

table1 = table1.rename(
    columns={
        "model": "Model",
        "accuracy": "Accuracy (%)",
        "balanced_accuracy": "Balanced Accuracy (%)",
        "precision": "Precision (%)",
        "sensitivity": "Sensitivity (%)",
        "specificity": "Specificity (%)",
        "f1": "F1-score (%)",
        "roc_auc": "ROC-AUC (%)",
        "pr_auc": "PR-AUC (%)"
    }
)


# =============================================================================
# 12. TABLE 2 — MODEL IMPROVEMENT
# =============================================================================

table2 = improvement_df.copy()

table2 = table2.rename(
    columns={
        "comparison": "Comparison",
        "metric": "Metric",
        "percentage_point_difference": "Difference (pp)"
    }
)


# =============================================================================
# 13. TABLE 3 — PAIRED STATISTICAL COMPARISON
# =============================================================================

table3 = paired_df[
    [
        "comparison",
        "accuracy_difference_pp",
        "both_correct",
        "both_wrong",
        "A_correct_B_wrong",
        "A_wrong_B_correct",
        "mcnemar_exact_p"
    ]
].copy()

table3 = table3.rename(
    columns={
        "comparison": "Comparison",
        "accuracy_difference_pp": "Accuracy Difference (pp)",
        "both_correct": "Both Correct",
        "both_wrong": "Both Wrong",
        "A_correct_B_wrong": "A Correct / B Wrong",
        "A_wrong_B_correct": "A Wrong / B Correct",
        "mcnemar_exact_p": "McNemar Exact p-value"
    }
)


# =============================================================================
# 14. TABLE 4 — BOOTSTRAP
# =============================================================================

table4 = bootstrap_df[
    [
        "comparison",
        "observed_difference_pp",
        "ci_95_low_pp",
        "ci_95_high_pp",
        "n_bootstrap"
    ]
].copy()

table4 = table4.rename(
    columns={
        "comparison": "Comparison",
        "observed_difference_pp": "Observed Difference (pp)",
        "ci_95_low_pp": "95% CI Lower (pp)",
        "ci_95_high_pp": "95% CI Upper (pp)",
        "n_bootstrap": "Bootstrap Resamples"
    }
)


# =============================================================================
# 15. TABLE 5 — CXR ERROR CORRECTION
# =============================================================================

table5 = error_correction_df.copy()

table5 = table5.rename(
    columns={
        "baseline": "Baseline Model",
        "baseline_errors": "Baseline Errors",
        "corrected_by_genomic": "Corrected by Genomic",
        "remaining_with_genomic": "Remaining with Genomic",
        "corrected_by_multimodal": "Corrected by Multimodal",
        "remaining_with_multimodal": "Remaining with Multimodal"
    }
)


# =============================================================================
# 16. TABLE 6 — THREE-MODEL CORRECTNESS
# =============================================================================

table6 = three_model_df.copy()

table6 = table6.rename(
    columns={
        "pattern": "Correctness Pattern",
        "count": "Cases",
        "percentage": "Percentage (%)"
    }
)


# =============================================================================
# 17. TABLE 7 — HARD PREDICTION AGREEMENT
# =============================================================================

table7 = agreement_df.copy()

table7 = table7.rename(
    columns={
        "comparison": "Comparison",
        "agreement_count": "Agreement Cases",
        "disagreement_count": "Disagreement Cases",
        "agreement_percent": "Agreement (%)"
    }
)


# =============================================================================
# 18. TABLE 8 — CXR GRAD-CAM QUANTITATIVE ANALYSIS
# =============================================================================

if xai_df.empty:

    raise RuntimeError(
        "Notebook 17 Grad-CAM quantitative table is empty."
    )

table8 = xai_df.copy()


# =============================================================================
# 19. TABLE 9 — MULTIMODAL MODALITY CONTRIBUTION
# =============================================================================

required_contribution_columns = [
    "condition_id",
    "target_binary",
    "official_probability_DR",
    "absolute_CXR_contribution",
    "absolute_genomic_contribution"
]

missing_columns = [
    c
    for c in required_contribution_columns
    if c not in modality_contribution_df.columns
]

if missing_columns:

    raise RuntimeError(
        "Notebook 18 contribution table is missing:\n"
        + "\n".join(missing_columns)
    )


mean_cxr = float(
    modality_contribution_df[
        "absolute_CXR_contribution"
    ].mean()
)

median_cxr = float(
    modality_contribution_df[
        "absolute_CXR_contribution"
    ].median()
)

mean_genomic = float(
    modality_contribution_df[
        "absolute_genomic_contribution"
    ].mean()
)

median_genomic = float(
    modality_contribution_df[
        "absolute_genomic_contribution"
    ].median()
)

cxr_dominant = int(
    (
        modality_contribution_df[
            "absolute_CXR_contribution"
        ]
        >
        modality_contribution_df[
            "absolute_genomic_contribution"
        ]
    ).sum()
)

genomic_dominant = int(
    (
        modality_contribution_df[
            "absolute_genomic_contribution"
        ]
        >
        modality_contribution_df[
            "absolute_CXR_contribution"
        ]
    ).sum()
)

equal_cases = int(
    np.isclose(
        modality_contribution_df[
            "absolute_CXR_contribution"
        ],
        modality_contribution_df[
            "absolute_genomic_contribution"
        ],
        atol=1e-12
    ).sum()
)


if not np.isclose(
    mean_cxr,
    0.031719,
    atol=1e-5
):

    raise RuntimeError(
        "Unexpected mean CXR contribution."
    )


if not np.isclose(
    mean_genomic,
    0.357736,
    atol=1e-5
):

    raise RuntimeError(
        "Unexpected mean genomic contribution."
    )


if cxr_dominant != 1:

    raise RuntimeError(
        f"Expected CXR-dominant = 1, found {cxr_dominant}"
    )


if genomic_dominant != 395:

    raise RuntimeError(
        f"Expected genomic-dominant = 395, found {genomic_dominant}"
    )


if equal_cases != 0:

    raise RuntimeError(
        f"Expected equal = 0, found {equal_cases}"
    )


table9 = pd.DataFrame([

    {
        "Measure":
            "Mean |CXR contribution|",

        "Value":
            mean_cxr
    },

    {
        "Measure":
            "Median |CXR contribution|",

        "Value":
            median_cxr
    },

    {
        "Measure":
            "Mean |Genomic contribution|",

        "Value":
            mean_genomic
    },

    {
        "Measure":
            "Median |Genomic contribution|",

        "Value":
            median_genomic
    },

    {
        "Measure":
            "CXR-dominant cases",

        "Value":
            cxr_dominant
    },

    {
        "Measure":
            "Genomic-dominant cases",

        "Value":
            genomic_dominant
    },

    {
        "Measure":
            "Equal contribution cases",

        "Value":
            equal_cases
    }

])


# =============================================================================
# 20. TABLE 10 — FINAL COHORT
# =============================================================================

table10 = pd.DataFrame([

    {
        "Measure":
            "Total conditions",
        "Value":
            1976
    },

    {
        "Measure":
            "DS conditions",
        "Value":
            704
    },

    {
        "Measure":
            "DR conditions",
        "Value":
            1272
    },

    {
        "Measure":
            "Training conditions",
        "Value":
            1185
    },

    {
        "Measure":
            "Validation conditions",
        "Value":
            395
    },

    {
        "Measure":
            "Test conditions",
        "Value":
            396
    },

    {
        "Measure":
            "Test DS",
        "Value":
            141
    },

    {
        "Measure":
            "Test DR",
        "Value":
            255
    },

    {
        "Measure":
            "Target encoding",
        "Value":
            "DS=0, DR=1"
    }

])


# =============================================================================
# 21. TABLE 11 — FINAL SCIENTIFIC RESULTS
# =============================================================================

cxr_row = performance_df[
    performance_df["model"] == "CXR-only"
].iloc[0]

genomic_row = performance_df[
    performance_df["model"] == "Genomic-only"
].iloc[0]

multimodal_row = performance_df[
    performance_df["model"] == "CXR + Genomic"
].iloc[0]


table11 = pd.DataFrame([

    {
        "Result":
            "CXR-only accuracy (%)",

        "Value":
            float(cxr_row["accuracy"] * 100)
    },

    {
        "Result":
            "Genomic-only accuracy (%)",

        "Value":
            float(genomic_row["accuracy"] * 100)
    },

    {
        "Result":
            "CXR + Genomic accuracy (%)",

        "Value":
            float(multimodal_row["accuracy"] * 100)
    },

    {
        "Result":
            "CXR → Multimodal accuracy gain (pp)",

        "Value":
            float(
                (
                    multimodal_row["accuracy"]
                    -
                    cxr_row["accuracy"]
                ) * 100
            )
    },

    {
        "Result":
            "CXR-only ROC-AUC",

        "Value":
            float(cxr_row["roc_auc"])
    },

    {
        "Result":
            "Genomic-only ROC-AUC",

        "Value":
            float(genomic_row["roc_auc"])
    },

    {
        "Result":
            "CXR + Genomic ROC-AUC",

        "Value":
            float(multimodal_row["roc_auc"])
    },

    {
        "Result":
            "Genomic → Multimodal ROC-AUC gain (pp)",

        "Value":
            float(
                (
                    multimodal_row["roc_auc"]
                    -
                    genomic_row["roc_auc"]
                ) * 100
            )
    },

    {
        "Result":
            "Genomic-only PR-AUC",

        "Value":
            float(genomic_row["pr_auc"])
    },

    {
        "Result":
            "CXR + Genomic PR-AUC",

        "Value":
            float(multimodal_row["pr_auc"])
    },

    {
        "Result":
            "Genomic → Multimodal PR-AUC gain (pp)",

        "Value":
            float(
                (
                    multimodal_row["pr_auc"]
                    -
                    genomic_row["pr_auc"]
                ) * 100
            )
    },

    {
        "Result":
            "CXR errors",

        "Value":
            122
    },

    {
        "Result":
            "Genomic errors",

        "Value":
            25
    },

    {
        "Result":
            "Multimodal errors",

        "Value":
            25
    },

    {
        "Result":
            "CXR errors corrected by Genomic",

        "Value":
            117
    },

    {
        "Result":
            "CXR errors corrected by Multimodal",

        "Value":
            117
    },

    {
        "Result":
            "Genomic / Multimodal hard agreement (%)",

        "Value":
            100.0
    }

])


# =============================================================================
# 22. SAVE TABLES
# =============================================================================

outputs = {

    "Table1_Final_Model_Performance.csv":
        table1,

    "Table2_Model_Performance_Differences.csv":
        table2,

    "Table3_Paired_Statistical_Comparison.csv":
        table3,

    "Table4_Paired_Bootstrap_Confidence_Intervals.csv":
        table4,

    "Table5_Error_Correction.csv":
        table5,

    "Table6_Three_Model_Correctness.csv":
        table6,

    "Table7_Hard_Prediction_Agreement.csv":
        table7,

    "Table8_CXR_GradCAM_Quantitative_Analysis.csv":
        table8,

    "Table9_Multimodal_Modality_Contribution.csv":
        table9,

    "Table10_Final_Cohort.csv":
        table10,

    "Table11_Final_Scientific_Results.csv":
        table11
}


for filename, df in outputs.items():

    output_path = (
        CELL4_ROOT
        / filename
    )

    df.to_csv(
        output_path,
        index=False
    )

    if not output_path.is_file():

        raise RuntimeError(
            f"Output was not created:\n{output_path}"
        )


# =============================================================================
# 23. FINAL AUDIT JSON
# =============================================================================

final_audit = {

    "status":
        "PASS",

    "notebook":
        "Notebook19",

    "cell":
        "Cell4",

    "frozen_cohort":
        {
            "total": 1976,
            "DS": 704,
            "DR": 1272,
            "train": 1185,
            "validation": 395,
            "test": 396,
            "test_DS": 141,
            "test_DR": 255
        },

    "performance":
        EXPECTED_VALUES,

    "error_analysis":
        {
            "CXR_errors": 122,
            "Genomic_errors": 25,
            "Multimodal_errors": 25,
            "CXR_errors_corrected_by_Genomic": 117,
            "CXR_errors_corrected_by_Multimodal": 117
        },

    "modality_contribution":
        {
            "mean_CXR": mean_cxr,
            "median_CXR": median_cxr,
            "mean_Genomic": mean_genomic,
            "median_Genomic": median_genomic,
            "CXR_dominant": cxr_dominant,
            "Genomic_dominant": genomic_dominant,
            "Equal": equal_cases
        },

    "hard_prediction_agreement":
        {
            "Genomic_vs_Multimodal_cases": 396,
            "agreement_percent": 100.0
        },

    "constraints":
        {
            "training": False,
            "fine_tuning": False,
            "model_inference": False,
            "checkpoint_selection": False,
            "threshold_tuning": False,
            "test_predictions_modified": False,
            "test_re_evaluated": False
        },

    "notebook17_xai_source":
        str(NB17_XAI),

    "publication_tables":
        list(outputs.keys())
}


FINAL_AUDIT = (
    CELL4_ROOT
    / "Cell4_Final_Publication_Results_Audit.json"
)

with open(
    FINAL_AUDIT,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        final_audit,
        f,
        indent=4
    )


# =============================================================================
# 24. MANIFEST
# =============================================================================

manifest = pd.DataFrame([

    {
        "filename": filename,
        "exists": (
            CELL4_ROOT / filename
        ).is_file(),
        "size_bytes": (
            (CELL4_ROOT / filename).stat().st_size
            if (CELL4_ROOT / filename).is_file()
            else 0
        )
    }

    for filename in outputs.keys()

])

MANIFEST_PATH = (
    CELL4_ROOT
    / "Cell4_Publication_Package_Manifest.csv"
)

manifest.to_csv(
    MANIFEST_PATH,
    index=False
)


# =============================================================================
# 25. FINAL CHECK
# =============================================================================

for filename in outputs.keys():

    path = (
        CELL4_ROOT
        / filename
    )

    if not path.is_file():

        raise RuntimeError(
            f"Missing output:\n{path}"
        )

if not FINAL_AUDIT.is_file():

    raise RuntimeError(
        "Final audit JSON missing."
    )

if not MANIFEST_PATH.is_file():

    raise RuntimeError(
        "Publication manifest missing."
    )


# =============================================================================
# 26. DISPLAY
# =============================================================================

print("\n")
print("=" * 100)
print("FINAL MODEL PERFORMANCE")
print("=" * 100)

display(table1)


print("\n")
print("=" * 100)
print("PAIRED STATISTICAL COMPARISON")
print("=" * 100)

display(table3)


print("\n")
print("=" * 100)
print("ERROR CORRECTION")
print("=" * 100)

display(table5)


print("\n")
print("=" * 100)
print("MULTIMODAL MODALITY CONTRIBUTION")
print("=" * 100)

display(table9)


print("\n")
print("=" * 100)
print("FINAL COHORT")
print("=" * 100)

display(table10)


# =============================================================================
# 27. FINAL STATUS
# =============================================================================

print("\n")
print("=" * 100)
print("NOTEBOOK 19 — CELL 4 STATUS: PASS")
print("=" * 100)

print("Frozen cohort                    : 1976")
print("Train / Validation / Test       : 1185 / 395 / 396")
print("Test DS / DR                    : 141 / 255")
print("Publication tables              : 11")
print("Notebook 17 Grad-CAM            : INCLUDED")
print("Notebook 18 modality analysis   : INCLUDED")
print("Paired statistical analysis     : INCLUDED")
print("Error analysis                  : INCLUDED")
print("Final audit JSON                : CREATED")
print("Publication manifest            : CREATED")

print("\n")
print("Training performed              : NO")
print("Fine-tuning performed           : NO")
print("Model inference performed       : NO")
print("Checkpoint selection            : NO")
print("Threshold tuning               : NO")
print("Test predictions modified      : NO")
print("Test re-evaluation              : NO")

print("\n")
print("Notebook 17 XAI source:")
print(NB17_XAI)

print("\n")
print("Output directory:")
print(CELL4_ROOT)

print("\n")
print("=" * 100)
print("NOTEBOOK 19 — CELL 4 COMPLETE")
print("=" * 100)

====================================================================================================
NOTEBOOK 19 — CELL 4
FINAL PUBLICATION-READY RESULTS PACKAGE
====================================================================================================


====================================================================================================
INPUT ARTIFACT AUDIT
====================================================================================================
Cell1 performance                       : PASS
Cell1 audit                             : PASS
Cell2 performance                       : PASS
Cell2 improvement                       : PASS
Cell2 summary                           : PASS
Cell2 findings                          : PASS
Cell2 JSON                              : PASS
Cell3 paired                            : PASS
Cell3 bootstrap                         : PASS
Cell3 error overlap                     : PASS
Cell3 error correction                  : PASS
Cell3 three-model                       : PASS
Cell3 agreement                         : PASS
Cell3 JSON                              : PASS
Notebook17 quantitative GradCAM         : PASS
Notebook18 summary                      : PASS
Notebook18 audit                        : PASS
Notebook18 contribution                 : PASS
Notebook18 statistics                   : PASS


====================================================================================================
FINAL MODEL PERFORMANCE
====================================================================================================

,Model,Accuracy (%),Balanced Accuracy (%),Precision (%),Sensitivity (%),Specificity (%),F1-score (%),ROC-AUC (%),PR-AUC (%)
0,CXR-only,69.1919,62.9203,72.2408,84.7059,41.1348,77.9783,71.5589,79.7732
1,Genomic-only,93.6869,94.3054,97.9167,92.1569,96.4539,94.9495,96.0298,98.1941
2,CXR + Genomic,93.6869,94.3054,97.9167,92.1569,96.4539,94.9495,97.1437,98.6393

====================================================================================================
PAIRED STATISTICAL COMPARISON
====================================================================================================

,Comparison,Accuracy Difference (pp),Both Correct,Both Wrong,A Correct / B Wrong,A Wrong / B Correct,McNemar Exact p-value
0,CXR-only vs Genomic-only,24.494949,254,5,20,117,7.157152e-18
1,CXR-only vs CXR + Genomic,24.494949,254,5,20,117,7.157152e-18
2,Genomic-only vs CXR + Genomic,0.000000,371,25,0,0,1.000000e+00

====================================================================================================
ERROR CORRECTION
====================================================================================================

,Baseline Model,Baseline Errors,Corrected by Genomic,Remaining with Genomic,Corrected by Multimodal,Remaining with Multimodal
0,CXR-only,122,117,5,117,5

====================================================================================================
MULTIMODAL MODALITY CONTRIBUTION
====================================================================================================

                         Measure       Value
0        Mean |CXR contribution|    0.031719
1      Median |CXR contribution|    0.018690
2    Mean |Genomic contribution|    0.357736
3  Median |Genomic contribution|    0.314102
4             CXR-dominant cases    1.000000
5         Genomic-dominant cases  395.000000
6       Equal contribution cases    0.000000

====================================================================================================
FINAL COHORT
====================================================================================================

                 Measure       Value
0       Total conditions        1976
1          DS conditions         704
2          DR conditions        1272
3    Training conditions        1185
4  Validation conditions         395
5        Test conditions         396
6                Test DS         141
7                Test DR         255
8        Target encoding  DS=0, DR=1

====================================================================================================
NOTEBOOK 19 — CELL 4 STATUS: PASS
====================================================================================================
Frozen cohort                    : 1976
Train / Validation / Test       : 1185 / 395 / 396
Test DS / DR                    : 141 / 255
Publication tables              : 11
Notebook 17 Grad-CAM            : INCLUDED
Notebook 18 modality analysis   : INCLUDED
Paired statistical analysis     : INCLUDED
Error analysis                  : INCLUDED
Final audit JSON                : CREATED
Publication manifest            : CREATED


Training performed              : NO
Fine-tuning performed           : NO
Model inference performed       : NO
Checkpoint selection            : NO
Threshold tuning               : NO
Test predictions modified      : NO
Test re-evaluation              : NO


Notebook 17 XAI source:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook17_Final_Explainability_Analysis\Cell3_GradCAM_Quantitative_Analysis\Notebook17_Cell3_GradCAM_Activation_Concentration.csv


Output directory:
C:\TBP\Metadata\Step_3B_8_CXR_CoAtNet_Preparation\QC\Clean_PSPNet_CXR_Cohort\FINAL_FROZEN_CLEAN_COHORT\Notebook19_Final_Research_Results_Integration\Cell4_Final_Publication_Results


====================================================================================================
NOTEBOOK 19 — CELL 4 COMPLETE
====================================================================================================